# Generated by Django 6.0.4 on 2026-06-22 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_product_conversion_factor_product_has_variants_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='compare_at_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Original price shown struck-through on the store. Leave blank if no discount.', max_digits=10, null=True),
        ),
    ]
