# Generated by Django 6.0.4 on 2026-07-31 07:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0013_company_cit_rate'),
        ('products', '0020_alter_stocktransaction_transaction_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabelPrintSetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('continuous_roll', models.BooleanField(default=True)),
                ('page_width_mm', models.DecimalField(decimal_places=2, default=110, max_digits=6)),
                ('page_height_mm', models.DecimalField(decimal_places=2, default=20, max_digits=6)),
                ('label_width_mm', models.DecimalField(decimal_places=2, default=33, max_digits=6)),
                ('label_height_mm', models.DecimalField(decimal_places=2, default=20, max_digits=6)),
                ('columns_per_row', models.PositiveSmallIntegerField(default=3)),
                ('rows_per_page', models.PositiveSmallIntegerField(default=1)),
                ('top_margin_mm', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('left_margin_mm', models.DecimalField(decimal_places=2, default=10, max_digits=6)),
                ('horizontal_gap_mm', models.DecimalField(decimal_places=2, default=2, max_digits=6)),
                ('vertical_gap_mm', models.DecimalField(decimal_places=2, default=2, max_digits=6)),
                ('padding_top_mm', models.DecimalField(decimal_places=2, default=1, max_digits=6)),
                ('padding_right_mm', models.DecimalField(decimal_places=2, default=1.5, max_digits=6)),
                ('padding_bottom_mm', models.DecimalField(decimal_places=2, default=1, max_digits=6)),
                ('padding_left_mm', models.DecimalField(decimal_places=2, default=1.5, max_digits=6)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='label_print_setting', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
