# Generated by Django 6.0.4 on 2026-08-04 01:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0026_alter_fixedassetdepreciationlog_options_and_more'),
        ('products', '0021_labelprintsetting'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='labelprintsetting',
            name='show_barcode',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='labelprintsetting',
            name='show_hscode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='labelprintsetting',
            name='show_price',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='labelprintsetting',
            name='show_sku',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='disposal_reason',
            field=models.CharField(blank=True, choices=[('DAMAGED', 'Damaged'), ('EXPIRED', 'Expired'), ('LOST', 'Lost'), ('THEFT', 'Theft'), ('OBSOLETE', 'Obsolete'), ('OTHER', 'Other')], help_text='NFRS 2: category of write-off. Only set when transaction_type=DISPOSAL.', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='journal_entry',
            field=models.ForeignKey(blank=True, help_text='The write-off journal entry posted for a DISPOSAL transaction.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookkeeping.journalentry'),
        ),
        migrations.AlterField(
            model_name='stocktransaction',
            name='transaction_type',
            field=models.CharField(choices=[('ADD', 'Add Stock'), ('REMOVE', 'Remove Stock'), ('ADJUST', 'Adjust Stock'), ('DISPOSAL', 'Disposal / Write-off')], max_length=20),
        ),
        migrations.CreateModel(
            name='StockLot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('qty_received', models.PositiveIntegerField()),
                ('qty_remaining', models.PositiveIntegerField()),
                ('unit_cost', models.DecimalField(decimal_places=4, max_digits=12)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('source_reference', models.CharField(blank=True, default='', max_length=100)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_lots', to='products.product')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['received_at'],
            },
        ),
        migrations.DeleteModel(
            name='StockDisposal',
        ),
    ]
