# Generated by Django 6.0.4 on 2026-08-03 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_stocklot'),
    ]

    operations = [
        migrations.AddField(
            model_name='labelprintsetting',
            name='show_barcode',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='labelprintsetting',
            name='show_hscode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='labelprintsetting',
            name='show_price',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='labelprintsetting',
            name='show_sku',
            field=models.BooleanField(default=False),
        ),
    ]
