# Generated by Django 6.0.4 on 2026-08-04 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_labelprintsetting_show_barcode_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='compare_at_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='nrv',
        ),
        migrations.RemoveField(
            model_name='product',
            name='vendor',
        ),
        # RenameField, not Remove+Add — sale_unit holds real FK data on every
        # product that must carry over to default_unit, not be dropped and
        # recreated null.
        migrations.RenameField(
            model_name='product',
            old_name='sale_unit',
            new_name='default_unit',
        ),
        migrations.AlterField(
            model_name='product',
            name='default_unit',
            field=models.ForeignKey(blank=True, help_text='Standard unit of measurement for inventory/stock tracking (e.g. Piece, Gram).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sold_products', to='products.unitofmeasure'),
        ),
    ]
