# Generated by Django 6.0.4 on 2026-08-25 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_remove_product_compare_at_price_remove_product_nrv_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='compare_at_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Original price used for sale/offer filtering', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='material',
            field=models.CharField(blank=True, default='', help_text='Primary material, e.g. Brass or Terracotta', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='occasion',
            field=models.CharField(blank=True, default='', help_text='Comma-separated occasions, e.g. Diwali, Daily Puja', max_length=200),
        ),
    ]
