# Generated by Django 6.0.4 on 2026-06-04 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0013_journalentryline_jel_account_type_idx_and_more'),
        ('payments', '0007_expense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='journal_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='bookkeeping.journalentry'),
        ),
    ]
