# Generated by Django 6.0.4 on 2026-06-16 06:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0014_journal_entry_reversal_fields'),
        ('company', '0013_company_cit_rate'),
        ('payments', '0010_expense_unique_reference'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('bank_name', models.CharField(max_length=150)),
                ('account_name', models.CharField(help_text='Account holder / title as per bank records.', max_length=150)),
                ('account_number', models.CharField(max_length=50)),
                ('branch_name', models.CharField(blank=True, default='', max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('ledger_account', models.OneToOneField(blank=True, help_text='Automatically assigned ledger account for this bank account.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_account', to='bookkeeping.ledgeraccount')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['bank_name'],
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='bank_account',
            field=models.ForeignKey(blank=True, help_text='Bank account this payment was received into / paid from (for BANK_TRANSFER/CHEQUE).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='payments.bankaccount'),
        ),
        migrations.AddField(
            model_name='vendorpayment',
            name='bank_account',
            field=models.ForeignKey(blank=True, help_text='Bank account this payment was sent from (for BANK_TRANSFER/CHEQUE).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_payments', to='payments.bankaccount'),
        ),
        migrations.AddConstraint(
            model_name='bankaccount',
            constraint=models.UniqueConstraint(fields=('company', 'account_number'), name='unique_bank_account_number_per_company'),
        ),
    ]
