# Generated by Django 6.0.4 on 2026-06-30 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0013_company_cit_rate'),
        ('payments', '0011_bankaccount_payment_bank_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='fiscal_year',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='company.fiscalyear'),
        ),
    ]
