"""Initial migration for orders app."""
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0009_invoice_branch'),
        ('company', '0007_company_order_manufacturing_flags'),
        ('customers', '0002_customer_text'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('order_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('order_date', models.DateField(default=django.utils.timezone.now)),
                ('expected_delivery_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[
                    ('DRAFT','Draft'),('CONFIRMED','Confirmed'),('PROCESSING','Processing'),
                    ('DISPATCHED','Dispatched'),('DELIVERED','Delivered'),
                    ('CANCELLED','Cancelled'),('RETURNED','Returned')],
                    default='DRAFT', max_length=15)),
                ('priority', models.CharField(choices=[
                    ('LOW','Low'),('NORMAL','Normal'),('HIGH','High'),('URGENT','Urgent')],
                    default='NORMAL', max_length=10)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('delivery_address', models.TextField(blank=True, null=True)),
                ('delivery_contact', models.CharField(blank=True, max_length=255, null=True)),
                ('delivery_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                    related_name='sales_orders', to='company.company')),
                ('branch', models.ForeignKey(blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='sales_orders', to='company.branch')),
                ('customer', models.ForeignKey(blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='sales_orders', to='customers.customer')),
                ('invoice', models.OneToOneField(blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='sales_order', to='billing.invoice')),
                ('created_by', models.ForeignKey(blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='created_salesorder', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='updated_salesorder', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='deleted_salesorder', to=settings.AUTH_USER_MODEL)),
            ],
            options={'ordering': ['-order_date', '-created_at']},
        ),
        migrations.CreateModel(
            name='SalesOrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('quantity', models.DecimalField(decimal_places=3, default=Decimal('1.000'), max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('tax_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                    related_name='items', to='orders.salesorder')),
                ('product', models.ForeignKey(blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL, to='products.product')),
                ('created_by', models.ForeignKey(blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='created_salesorderitem', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='updated_salesorderitem', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='deleted_salesorderitem', to=settings.AUTH_USER_MODEL)),
            ],
            options={'ordering': ['created_at']},
        ),
        migrations.CreateModel(
            name='DeliveryNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('delivery_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('dispatch_date', models.DateField(default=django.utils.timezone.now)),
                ('expected_delivery_date', models.DateField(blank=True, null=True)),
                ('actual_delivery_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[
                    ('PENDING','Pending'),('PACKED','Packed'),('DISPATCHED','Dispatched'),
                    ('IN_TRANSIT','In Transit'),('OUT_FOR_DELIVERY','Out for Delivery'),
                    ('DELIVERED','Delivered'),('FAILED','Delivery Failed'),('RETURNED','Returned')],
                    default='PENDING', max_length=20)),
                ('carrier_name', models.CharField(blank=True, max_length=255, null=True)),
                ('tracking_number', models.CharField(blank=True, max_length=100, null=True)),
                ('vehicle_number', models.CharField(blank=True, max_length=50, null=True)),
                ('driver_name', models.CharField(blank=True, max_length=255, null=True)),
                ('driver_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('delivery_address', models.TextField(blank=True, null=True)),
                ('delivery_contact', models.CharField(blank=True, max_length=255, null=True)),
                ('delivery_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('received_by', models.CharField(blank=True, max_length=255, null=True)),
                ('delivery_signature', models.ImageField(blank=True, null=True, upload_to='delivery_signatures/')),
                ('delivery_photo', models.ImageField(blank=True, null=True, upload_to='delivery_photos/')),
                ('notes', models.TextField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                    related_name='delivery_notes', to='company.company')),
                ('sales_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                    related_name='delivery_notes', to='orders.salesorder')),
                ('created_by', models.ForeignKey(blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='created_deliverynote', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='updated_deliverynote', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='deleted_deliverynote', to=settings.AUTH_USER_MODEL)),
            ],
            options={'ordering': ['-dispatch_date', '-created_at']},
        ),
        migrations.CreateModel(
            name='DeliveryNoteItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('quantity_delivered', models.DecimalField(decimal_places=3, max_digits=10)),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('delivery_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                    related_name='items', to='orders.deliverynote')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                    related_name='delivery_items', to='orders.salesorderitem')),
                ('created_by', models.ForeignKey(blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='created_deliverynoteitem', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='updated_deliverynoteitem', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='deleted_deliverynoteitem', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryTracking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('event_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[
                    ('PENDING','Pending'),('PACKED','Packed'),('DISPATCHED','Dispatched'),
                    ('IN_TRANSIT','In Transit'),('OUT_FOR_DELIVERY','Out for Delivery'),
                    ('DELIVERED','Delivered'),('FAILED','Delivery Failed'),('RETURNED','Returned')],
                    max_length=20)),
                ('location', models.CharField(blank=True, max_length=500, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('notes', models.CharField(blank=True, max_length=500, null=True)),
                ('updated_by_name', models.CharField(blank=True, max_length=255, null=True)),
                ('delivery_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                    related_name='tracking_events', to='orders.deliverynote')),
                ('created_by', models.ForeignKey(blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='created_deliverytracking', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='updated_deliverytracking', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='deleted_deliverytracking', to=settings.AUTH_USER_MODEL)),
            ],
            options={'ordering': ['-event_time']},
        ),
    ]
