# Generated by Django 6.0.4 on 2026-06-16 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_deliverynote_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverynote',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PACKED', 'Packed'), ('DISPATCHED', 'Dispatched'), ('IN_TRANSIT', 'In Transit'), ('OUT_FOR_DELIVERY', 'Out for Delivery'), ('DELIVERED', 'Delivered'), ('FAILED', 'Delivery Failed'), ('RETURNED', 'Returned'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='deliverytracking',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PACKED', 'Packed'), ('DISPATCHED', 'Dispatched'), ('IN_TRANSIT', 'In Transit'), ('OUT_FOR_DELIVERY', 'Out for Delivery'), ('DELIVERED', 'Delivered'), ('FAILED', 'Delivery Failed'), ('RETURNED', 'Returned'), ('CANCELLED', 'Cancelled')], max_length=20),
        ),
    ]
