# Generated by Django 6.0.4 on 2026-06-25 09:51

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_deliverynote_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='delivery_charge',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
