# Generated by Django 6.0.4 on 2026-07-06 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_sales_order_delivery_charge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorder',
            name='status',
            field=models.CharField(choices=[('CONFIRMED', 'Confirmed'), ('PROCESSING', 'Processing'), ('DISPATCHED', 'Dispatched'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled'), ('RETURNED', 'Returned')], default='CONFIRMED', max_length=15),
        ),
    ]
