# Generated by Django 6.0.4 on 2026-08-11 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0016_company_receipt_footer_text'),
        ('orders', '0006_salesorder_fiscal_year_salesorder_sequence_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverynote',
            name='fiscal_year',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_notes', to='company.fiscalyear'),
        ),
        migrations.AddField(
            model_name='deliverynote',
            name='sequence_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
