# Generated by Django 6.0.4 on 2026-09-22 12:49

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0031_vendorbill_tds_category_alter_invoice_status'),
        ('company', '0019_company_store_domain'),
        ('customers', '0006_alter_customer_email_alter_customer_phone_and_more'),
        ('orders', '0007_deliverynote_fiscal_year_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorder',
            name='order_date',
            field=models.DateField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='status',
            field=models.CharField(choices=[('CONFIRMED', 'Confirmed'), ('PROCESSING', 'Processing'), ('DISPATCHED', 'Dispatched'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled'), ('RETURNED', 'Returned')], db_index=True, default='CONFIRMED', max_length=15),
        ),
        migrations.AddIndex(
            model_name='salesorder',
            index=models.Index(fields=['company', 'status', 'order_date'], name='orders_so_co_status_date_idx'),
        ),
    ]
