# Generated by Django 6.0.4 on 2026-05-20 03:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0009_postgres_functions_triggers_views'),
        ('products', '0003_product_hscode'),
        ('purchasing', '0003_purchaseorderitem_hscode'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderitem',
            name='description',
            field=models.CharField(blank=True, help_text='Required for Service and Non-Stock items.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='expense_account',
            field=models.ForeignKey(blank=True, help_text='Expense/asset account to debit for Service and Non-Stock lines.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='po_items', to='bookkeeping.ledgeraccount'),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='item_type',
            field=models.CharField(choices=[('STOCK', 'Stock Item'), ('SERVICE', 'Service'), ('NON_STOCK', 'Non-Stock / Expense')], default='STOCK', help_text='Stock item updates inventory on receive; Service and Non-Stock do not.', max_length=10),
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
    ]
