# Generated by Django 6.0.4 on 2026-05-29 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0012_company_cbms_password_company_cbms_username_and_more'),
        ('purchasing', '0004_po_item_type_service_nonstock'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Branch this PO was raised from (optional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders', to='company.branch'),
        ),
    ]
