# Generated by Django 6.0.4 on 2026-07-20 06:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0013_company_cit_rate'),
        ('purchasing', '0006_alter_purchaseorder_status'),
        ('vendors', '0006_vendor_vat_registered'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='fiscal_year',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders', to='company.fiscalyear'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='sequence_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='purchaseorder',
            constraint=models.UniqueConstraint(condition=models.Q(('sequence_number__isnull', False)), fields=('company', 'fiscal_year', 'sequence_number'), name='unique_po_seq_per_company_fy'),
        ),
    ]
