# Generated by Django 6.0.4 on 2026-08-04 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_remove_product_compare_at_price_remove_product_nrv_and_more'),
        ('purchasing', '0007_purchaseorder_fiscal_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderitem',
            name='conversion_factor_override',
            field=models.DecimalField(blank=True, decimal_places=4, help_text="Overrides the product's conversion_factor for this line only, if set.", max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='conversion_unit',
            field=models.ForeignKey(blank=True, help_text="Unit this line converts into for stock keeping. Defaults to the product's default_unit if not set.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='po_item_conversion_unit', to='products.unitofmeasure'),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='purchase_unit',
            field=models.ForeignKey(blank=True, help_text="Unit this line was purchased in. Defaults to the product's purchase_unit if not set.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='po_item_purchase_unit', to='products.unitofmeasure'),
        ),
    ]
