"""Initial migration for projects app."""
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0009_invoice_branch'),
        ('bookkeeping', '0009_postgres_functions_triggers_views'),
        ('company', '0006_company_organisation_type_vat'),
        ('payments', '0005_payment_branch'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # ── CostCentre ────────────────────────────────────────────────────
        migrations.CreateModel(
            name='CostCentre',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                    related_name='cost_centres', to='company.company')),
                ('parent', models.ForeignKey(blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='children', to='projects.costcentre')),
                ('created_by', models.ForeignKey(blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='created_costcentre', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='updated_costcentre', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='deleted_costcentre', to=settings.AUTH_USER_MODEL)),
            ],
            options={'ordering': ['name'], 'unique_together': {('company', 'name')}},
        ),

        # ── Project ───────────────────────────────────────────────────────
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, max_length=30, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('client_name', models.CharField(blank=True, max_length=255, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[
                    ('PLANNING','Planning'),('ACTIVE','Active'),('ON_HOLD','On Hold'),
                    ('COMPLETED','Completed'),('CANCELLED','Cancelled')],
                    default='PLANNING', max_length=15)),
                ('budget_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('currency', models.CharField(default='NPR', max_length=5)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                    related_name='projects', to='company.company')),
                ('cost_centre', models.ForeignKey(blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='projects', to='projects.costcentre')),
                ('created_by', models.ForeignKey(blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='created_project', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='updated_project', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='deleted_project', to=settings.AUTH_USER_MODEL)),
            ],
            options={'ordering': ['-start_date', 'name'],
                     'unique_together': {('company', 'code')}},
        ),

        # ── ProjectExpense ────────────────────────────────────────────────
        migrations.CreateModel(
            name='ProjectExpense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('description', models.CharField(max_length=500)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('expense_date', models.DateField(default=django.utils.timezone.now)),
                ('reference', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                    related_name='expenses', to='projects.project')),
                ('cost_centre', models.ForeignKey(blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='expenses', to='projects.costcentre')),
                ('ledger_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                    to='bookkeeping.ledgeraccount')),
                ('vendor_bill', models.ForeignKey(blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='project_expenses', to='billing.vendorbill')),
                ('payment', models.ForeignKey(blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='project_expenses', to='payments.payment')),
                ('created_by', models.ForeignKey(blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='created_projectexpense', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='updated_projectexpense', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='deleted_projectexpense', to=settings.AUTH_USER_MODEL)),
            ],
            options={'ordering': ['-expense_date']},
        ),

        # ── ProjectRevenue ────────────────────────────────────────────────
        migrations.CreateModel(
            name='ProjectRevenue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('description', models.CharField(max_length=500)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('revenue_date', models.DateField(default=django.utils.timezone.now)),
                ('reference', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                    related_name='revenues', to='projects.project')),
                ('invoice', models.ForeignKey(blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='project_revenues', to='billing.invoice')),
                ('created_by', models.ForeignKey(blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='created_projectrevenue', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='updated_projectrevenue', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='deleted_projectrevenue', to=settings.AUTH_USER_MODEL)),
            ],
            options={'ordering': ['-revenue_date']},
        ),

        # ── Budget ────────────────────────────────────────────────────────
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('budget_type', models.CharField(choices=[
                    ('REVENUE','Revenue Budget'),('EXPENSE','Expense Budget'),('CAPEX','Capital Expenditure')],
                    default='EXPENSE', max_length=10)),
                ('name', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                    related_name='budgets', to='company.company')),
                ('fiscal_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                    related_name='budgets', to='company.fiscalyear')),
                ('cost_centre', models.ForeignKey(blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='budgets', to='projects.costcentre')),
                ('project', models.ForeignKey(blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='budgets', to='projects.project')),
                ('ledger_account', models.ForeignKey(blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='budgets', to='bookkeeping.ledgeraccount')),
                ('created_by', models.ForeignKey(blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='created_budget', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='updated_budget', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='deleted_budget', to=settings.AUTH_USER_MODEL)),
            ],
            options={'ordering': ['period_start', 'name']},
        ),

        # ── Forecast ──────────────────────────────────────────────────────
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('forecast_type', models.CharField(choices=[
                    ('REVENUE','Revenue Forecast'),('EXPENSE','Expense Forecast'),
                    ('CASHFLOW','Cash Flow Forecast')],
                    default='REVENUE', max_length=10)),
                ('name', models.CharField(max_length=255)),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('forecast_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('notes', models.TextField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                    related_name='forecasts', to='company.company')),
                ('fiscal_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                    related_name='forecasts', to='company.fiscalyear')),
                ('cost_centre', models.ForeignKey(blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='forecasts', to='projects.costcentre')),
                ('project', models.ForeignKey(blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='forecasts', to='projects.project')),
                ('ledger_account', models.ForeignKey(blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='forecasts', to='bookkeeping.ledgeraccount')),
                ('created_by', models.ForeignKey(blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='created_forecast', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='updated_forecast', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='deleted_forecast', to=settings.AUTH_USER_MODEL)),
            ],
            options={'ordering': ['year', 'month'],
                     'unique_together': {('company','fiscal_year','forecast_type',
                                          'ledger_account','cost_centre','project','year','month')}},
        ),
    ]
