# Generated by Django 5.2.3 on 2025-07-02 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0007_ledgeraccount_system_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ledgeraccount',
            name='opening_type',
        ),
    ]
