# Generated by Django 6.0.4 on 2026-05-29 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0010_fix_balance_check_trigger_deferrable'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledgeraccount',
            name='is_current',
            field=models.BooleanField(default=True, help_text='NFRS: True = Current asset/liability (≤12 months). False = Non-current. Used for Balance Sheet classification.'),
        ),
    ]
