# Generated by Django 6.0.4 on 2026-06-04 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0013_journalentryline_jel_account_type_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='is_reversed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='reversal_of',
            field=models.ForeignKey(blank=True, help_text='Points to the original entry this entry reverses.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversals', to='bookkeeping.journalentry'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='reversed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='reversed_reason',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
