# Generated by Django 6.0.4 on 2026-07-30 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0020_backfill_normal_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='journal_type',
            field=models.CharField(choices=[('GENERAL', 'General / Standard'), ('OPENING', 'Opening Balance'), ('ADJUSTING', 'Adjusting Entry'), ('CLOSING', 'Closing Entry'), ('TRANSFER', 'Transfer / Contra'), ('PROVISION', 'Provision & Write-off'), ('DEPRECIATION', 'Depreciation'), ('DISPOSAL', 'Asset Disposal'), ('REVERSAL', 'Reversal')], default='GENERAL', help_text='NFRS classification for audit trail and filtering — does not affect posting mechanics.', max_length=15),
        ),
    ]
