# Generated by Django 6.0.4 on 2026-07-30 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0022_fn_close_period_journal_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentryline',
            name='cleared_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='journalentryline',
            name='is_cleared',
            field=models.BooleanField(default=False),
        ),
    ]
