# Generated by Django 6.0.4 on 2026-04-29

from django.db import migrations, models
import decimal


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_invoiceitem_hscode_vendorbillitem_hscode'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=decimal.Decimal('0.00'), help_text='Item discount percentage', max_digits=5),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=decimal.Decimal('0.00'), help_text='Item discount amount', max_digits=10),
        ),
    ]
