# Generated by Django 6.0.4 on 2026-05-03 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_invoice_branch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='vendorbill',
            name='branch',
        ),
    ]
