# Generated by Django 6.0.4 on 2026-05-22 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0013_re_add_invoice_status_column'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='item_type',
            field=models.CharField(choices=[('product', 'Item'), ('service', 'Service'), ('package', 'Package'), ('other', 'Other')], default='product', max_length=10),
        ),
    ]
