# Generated by Django 6.0.4 on 2026-06-25 09:42

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0022_vendorbill_audit_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditnote',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='VAT/tax portion of this note. Pro-rated from the linked invoice when available.', max_digits=10),
        ),
        migrations.AddField(
            model_name='debitnote',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='VAT/tax portion of this note. Pro-rated from the linked invoice when available.', max_digits=10),
        ),
    ]
