# Generated by Django 6.0.4 on 2026-06-30 15:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def drop_old_invoice_sequence_constraint(apps, schema_editor):
    Invoice = apps.get_model('billing', 'Invoice')
    constraint_name = 'unique_invoice_seq_per_company'
    table_name = Invoice._meta.db_table

    if schema_editor.connection.vendor == 'mysql':
        with schema_editor.connection.cursor() as cursor:
            cursor.execute(
                """
                SELECT COUNT(*)
                FROM information_schema.statistics
                WHERE table_schema = DATABASE()
                  AND table_name = %s
                  AND index_name = %s
                """,
                [table_name, constraint_name],
            )
            exists = cursor.fetchone()[0] > 0
        if exists:
            schema_editor.execute(
                f"ALTER TABLE `{table_name}` DROP INDEX `{constraint_name}`"
            )
        return

    constraint = models.UniqueConstraint(
        fields=('company', 'sequence_number'),
        name=constraint_name,
    )
    schema_editor.remove_constraint(Invoice, constraint)


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0023_credit_debit_note_tax_amount'),
        ('company', '0013_company_cit_rate'),
        ('customers', '0005_customer_ref_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    drop_old_invoice_sequence_constraint,
                    migrations.RunPython.noop,
                ),
            ],
            state_operations=[
                migrations.RemoveConstraint(
                    model_name='invoice',
                    name='unique_invoice_seq_per_company',
                ),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='fiscal_year',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='company.fiscalyear'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(condition=models.Q(('sequence_number__isnull', False)), fields=('company', 'fiscal_year', 'sequence_number'), name='unique_invoice_seq_per_company_fy'),
        ),
    ]
