# Generated by Django 6.0.4 on 2026-07-02 09:18

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0024_invoice_fiscal_year_sequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorbill',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='VAT/tax amount charged on this bill.', max_digits=10),
        ),
        migrations.AddField(
            model_name='vendorbill',
            name='tax_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='VAT/tax rate applied to this bill (e.g. 13.00).', max_digits=5),
        ),
    ]
