# Generated by Django 5.2.3 on 2025-07-02 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='text',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
