# Generated by Django 6.0.4 on 2026-05-29 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='pan_number',
            field=models.CharField(blank=True, help_text='PAN number for VAT/e-billing (buyer_pan in CBMS).', max_length=20, null=True),
        ),
    ]
