# Generated by Django 6.0.4 on 2026-06-21 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_phone_null_unique'),
        ('pos', '0003_alter_possale_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='ref_by',
            field=models.ForeignKey(blank=True, help_text='Person who referred this customer.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_customers', to='pos.referrer'),
        ),
    ]
