# Generated by Django 6.0.4 on 2026-08-18 11:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0028_tdsrate_tdsdeduction_and_more'),
        ('company', '0017_company_enable_ssf'),
        ('customers', '0005_customer_ref_by'),
        ('pos', '0005_alter_possale_payment_method'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(condition=models.Q(('email__isnull', False)), fields=('company', 'email'), name='unique_customer_email_per_company'),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(condition=models.Q(('phone__isnull', False)), fields=('company', 'phone'), name='unique_customer_phone_per_company'),
        ),
    ]
