# Generated by Django 4.2.12 on 2025-06-23 03:33

from django.db import migrations


def fix_permission_sync(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    RolePermission = apps.get_model('accounts', 'RolePermission')
    Permission = apps.get_model('auth', 'Permission')
    ContentType = apps.get_model('contenttypes', 'ContentType')

    for group in Group.objects.all():
        group.permissions.clear()

        role_perms = RolePermission.objects.filter(group=group)

        for role_perm in role_perms:
            perms = []
            content_type = role_perm.content_type

            if role_perm.can_view:
                perms.append(f'view_{content_type.model}')
            if role_perm.can_add:
                perms.append(f'add_{content_type.model}')
            if role_perm.can_change:
                perms.append(f'change_{content_type.model}')
            if role_perm.can_delete:
                perms.append(f'delete_{content_type.model}')

            for codename in perms:
                try:
                    permission = Permission.objects.get(
                        content_type=content_type,
                        codename=codename
                    )
                    group.permissions.add(permission)
                except Permission.DoesNotExist:
                    continue

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.RunPython(fix_permission_sync),
    ]
