# Generated by Django 6.0.4 on 2026-05-03 04:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_fix_permission_sync'),
        ('company', '0008_extend_employee_and_new_hr_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Branch this user belongs to. Leave blank to allow access to all branches within the company.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='company.branch'),
        ),
    ]
