# Generated by Django 6.0.4 on 2026-05-16 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_add_branch_to_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_company_admin',
            field=models.BooleanField(default=False, help_text='Designates this user as the administrator for their company. Company admins can create and manage users within their company.'),
        ),
    ]
