# Generated by Django 4.2.12 on 2025-06-22 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0002_alter_ledgeraccount_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledgeraccount',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddConstraint(
            model_name='ledgeraccount',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='unique_ledgeraccount_code_per_company'),
        ),
    ]
