# Generated by Django 5.2.3 on 2025-06-25 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0003_alter_ledgeraccount_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentryline',
            name='narration',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='description',
            field=models.CharField(blank=True, max_length=700, null=True),
        ),
    ]
