# Generated by Django 5.2.3 on 2025-06-30 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0005_journalentryline_amount_positive'),
        ('company', '0003_fiscalyear_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledgeraccount',
            name='opening_type',
            field=models.CharField(blank=True, choices=[('DEBIT', 'Debit'), ('CREDIT', 'Credit')], max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='LedgerOpeningBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_type', models.CharField(choices=[('DEBIT', 'Debit'), ('CREDIT', 'Credit')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opening_balances', to='bookkeeping.ledgeraccount')),
                ('fiscal_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.fiscalyear')),
            ],
            options={
                'unique_together': {('account', 'fiscal_year')},
            },
        ),
    ]
