# Generated by Django 6.0.4 on 2026-07-26 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0020_backfill_normal_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ledgeraccount',
            name='normal_balance',
        ),
    ]
