# Generated by Django 6.0.4 on 2026-07-31 06:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0023_journalentryline_cleared_date_and_more'),
        ('company', '0013_company_cit_rate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrepaidExpense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('start_date', models.DateField(help_text='First day of the period this prepayment covers')),
                ('end_date', models.DateField(help_text='Last day of the period this prepayment covers')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('FULLY_AMORTIZED', 'Fully Amortized')], default='ACTIVE', max_length=16)),
                ('accumulated_amortization', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('amortization_expense_account', models.ForeignKey(blank=True, help_text='Expense account amortization is charged to. Auto-created if blank.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prepaid_expenses_expense', to='bookkeeping.ledgeraccount')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prepaid_expenses', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('paid_from_account', models.ForeignKey(help_text='Bank/Cash account the initial prepayment was paid from.', on_delete=django.db.models.deletion.PROTECT, related_name='prepaid_expenses_paid_from', to='bookkeeping.ledgeraccount')),
                ('prepaid_asset_account', models.ForeignKey(blank=True, help_text='Prepaid Expense account (ASSET type). Auto-created if blank.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prepaid_expenses_asset', to='bookkeeping.ledgeraccount')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='PrepaidExpenseAmortizationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookkeeping.journalentry')),
                ('prepaid_expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amortization_logs', to='bookkeeping.prepaidexpense')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-period_end'],
            },
        ),
    ]
