# Generated by Django 6.0.4 on 2026-08-04 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0025_journalentry_db_defaults_for_raw_sql_inserts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fixedassetdepreciationlog',
            options={'ordering': ['-period_end']},
        ),
        migrations.AddField(
            model_name='journalentry',
            name='journal_type',
            field=models.CharField(choices=[('GENERAL', 'General / Standard'), ('OPENING', 'Opening Balance'), ('ADJUSTING', 'Adjusting Entry'), ('CLOSING', 'Closing Entry'), ('TRANSFER', 'Transfer / Contra'), ('PROVISION', 'Provision & Write-off'), ('DEPRECIATION', 'Depreciation'), ('DISPOSAL', 'Asset Disposal'), ('REVERSAL', 'Reversal')], default='GENERAL', help_text='NFRS classification for audit trail and filtering — does not affect posting mechanics.', max_length=15),
        ),
        migrations.AddField(
            model_name='ledgeraccount',
            name='normal_balance',
            field=models.CharField(blank=True, choices=[('DEBIT', 'Debit'), ('CREDIT', 'Credit')], help_text='NFRS: the entry_type (DEBIT/CREDIT) that increases this account. Auto-derived from account_type if left blank.', max_length=10),
        ),
    ]
