# Generated by Django 6.0.4 on 2026-07-30 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0026_alter_fixedassetdepreciationlog_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentryline',
            name='is_cleared',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='journalentryline',
            name='cleared_date',
            field=models.DateField(blank=True, help_text='The date this line cleared on the bank statement.', null=True),
        ),
    ]
