# Generated by Django 6.0.4 on 2026-08-26 10:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0028_tdsrate_tdsdeduction_and_more'),
        ('company', '0018_company_po_approval_threshold'),
        ('customers', '0006_alter_customer_email_alter_customer_phone_and_more'),
        ('vendors', '0006_vendor_vat_registered'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fixedasset',
            name='ird_pool',
            field=models.CharField(blank=True, choices=[('A', 'Pool A — Buildings, structures (5%)'), ('B', 'Pool B — Furniture, fixtures, office equipment (25%)'), ('C', 'Pool C — Vehicles, construction/earthmoving equipment (20%)'), ('D', 'Pool D — Computers, fittings, plant & machinery n.e.c. (15%)'), ('E', 'Pool E — Intangible assets (per useful life; straight-line)')], help_text='Income Tax Act Schedule 2 depreciation pool — for the pooled tax depreciation schedule (D1/D2/D3), separate from NFRS book depreciation above.', max_length=1, null=True),
        ),
        migrations.CreateModel(
            name='BalanceConfirmationRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('as_of_date', models.DateField()),
                ('balance', models.DecimalField(decimal_places=2, help_text='Ledger balance as of as_of_date, positive = party owes company', max_digits=14)),
                ('status', models.CharField(choices=[('PENDING', 'Pending — not sent'), ('SENT', 'Sent to party'), ('CONFIRMED', 'Confirmed by party'), ('DISPUTED', 'Disputed by party')], default='PENDING', max_length=10)),
                ('sent_date', models.DateField(blank=True, null=True)),
                ('confirmed_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance_confirmations', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='balance_confirmations', to='customers.customer')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='balance_confirmations', to='vendors.vendor')),
            ],
            options={
                'ordering': ['-as_of_date'],
            },
        ),
    ]
