# Generated by Django 6.0.4 on 2026-09-22 13:11

import django.db.models.deletion
from django.db import migrations, models

# journalentryline.amount is used by vw_trial_balance, vw_income_statement,
# and vw_balance_sheet_summary (apps/bookkeeping/migrations/0009). Postgres
# refuses to ALTER a column type while a view rule depends on it, so those
# three views are dropped before the AlterField and recreated after, with
# the exact same definitions as in migration 0009.

_DROP_DEPENDENT_VIEWS = """
DROP VIEW IF EXISTS vw_balance_sheet_summary;
DROP VIEW IF EXISTS vw_income_statement;
DROP VIEW IF EXISTS vw_trial_balance;
"""

_RECREATE_DEPENDENT_VIEWS = """
CREATE OR REPLACE VIEW vw_trial_balance AS
SELECT
    la.company_id,
    la.id                                                           AS account_id,
    la.code                                                         AS account_code,
    la.name                                                         AS account_name,
    la.account_type,
    COALESCE(SUM(jel.amount) FILTER (WHERE jel.entry_type='DEBIT'),  0) AS total_debits,
    COALESCE(SUM(jel.amount) FILTER (WHERE jel.entry_type='CREDIT'), 0) AS total_credits,
    CASE
        WHEN la.account_type IN ('ASSET','EXPENSE') THEN
            COALESCE(SUM(jel.amount) FILTER (WHERE jel.entry_type='DEBIT'),  0) -
            COALESCE(SUM(jel.amount) FILTER (WHERE jel.entry_type='CREDIT'), 0)
        ELSE
            COALESCE(SUM(jel.amount) FILTER (WHERE jel.entry_type='CREDIT'), 0) -
            COALESCE(SUM(jel.amount) FILTER (WHERE jel.entry_type='DEBIT'),  0)
    END AS net_balance
FROM bookkeeping_ledgeraccount la
LEFT JOIN bookkeeping_journalentryline jel ON jel.account_id=la.id AND jel.is_deleted=FALSE
LEFT JOIN bookkeeping_journalentry     je  ON je.id=jel.journal_entry_id AND je.is_deleted=FALSE
WHERE la.is_deleted=FALSE
GROUP BY la.company_id, la.id, la.code, la.name, la.account_type
ORDER BY la.company_id, la.account_type, la.code NULLS LAST, la.name;

CREATE OR REPLACE VIEW vw_income_statement AS
SELECT
    je.company_id,
    la.account_type,
    la.id   AS account_id,
    la.name AS account_name,
    la.code AS account_code,
    COALESCE(SUM(jel.amount) FILTER (WHERE jel.entry_type='CREDIT'), 0) AS credit_total,
    COALESCE(SUM(jel.amount) FILTER (WHERE jel.entry_type='DEBIT'),  0) AS debit_total,
    CASE la.account_type
        WHEN 'REVENUE' THEN
            COALESCE(SUM(jel.amount) FILTER (WHERE jel.entry_type='CREDIT'), 0) -
            COALESCE(SUM(jel.amount) FILTER (WHERE jel.entry_type='DEBIT'),  0)
        WHEN 'EXPENSE' THEN
            COALESCE(SUM(jel.amount) FILTER (WHERE jel.entry_type='DEBIT'),  0) -
            COALESCE(SUM(jel.amount) FILTER (WHERE jel.entry_type='CREDIT'), 0)
        ELSE 0
    END AS net_amount,
    je.date
FROM bookkeeping_journalentryline jel
JOIN bookkeeping_journalentry  je  ON je.id=jel.journal_entry_id AND je.is_deleted=FALSE
JOIN bookkeeping_ledgeraccount la  ON la.id=jel.account_id       AND la.is_deleted=FALSE
WHERE jel.is_deleted=FALSE AND la.account_type IN ('REVENUE','EXPENSE')
GROUP BY je.company_id, la.account_type, la.id, la.name, la.code, je.date
ORDER BY je.company_id, je.date, la.account_type, la.name;

CREATE OR REPLACE VIEW vw_balance_sheet_summary AS
SELECT
    la.company_id,
    la.account_type,
    COALESCE(SUM(jel.amount) FILTER (WHERE jel.entry_type='DEBIT'),  0) AS total_debits,
    COALESCE(SUM(jel.amount) FILTER (WHERE jel.entry_type='CREDIT'), 0) AS total_credits,
    CASE la.account_type
        WHEN 'ASSET' THEN
            COALESCE(SUM(jel.amount) FILTER (WHERE jel.entry_type='DEBIT'),  0) -
            COALESCE(SUM(jel.amount) FILTER (WHERE jel.entry_type='CREDIT'), 0)
        ELSE
            COALESCE(SUM(jel.amount) FILTER (WHERE jel.entry_type='CREDIT'), 0) -
            COALESCE(SUM(jel.amount) FILTER (WHERE jel.entry_type='DEBIT'),  0)
    END AS net_balance
FROM bookkeeping_ledgeraccount la
LEFT JOIN bookkeeping_journalentryline jel ON jel.account_id=la.id AND jel.is_deleted=FALSE
LEFT JOIN bookkeeping_journalentry     je  ON je.id=jel.journal_entry_id AND je.is_deleted=FALSE
WHERE la.is_deleted=FALSE AND la.account_type IN ('ASSET','LIABILITY','EQUITY')
GROUP BY la.company_id, la.account_type
ORDER BY la.company_id, la.account_type;
"""


def _drop_views(apps, schema_editor):
    if schema_editor.connection.vendor != 'postgresql':
        return
    schema_editor.execute(_DROP_DEPENDENT_VIEWS)


def _recreate_views(apps, schema_editor):
    if schema_editor.connection.vendor != 'postgresql':
        return
    schema_editor.execute(_RECREATE_DEPENDENT_VIEWS)


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0029_fixedasset_ird_pool_balanceconfirmationrequest'),
        ('company', '0019_company_store_domain'),
    ]

    operations = [
        migrations.RunPython(_drop_views, migrations.RunPython.noop),
        migrations.AddField(
            model_name='journalentry',
            name='fiscal_year',
            field=models.ForeignKey(blank=True, help_text='Auto-resolved from date on first save. Scopes voucher_no numbering.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_entries', to='company.fiscalyear'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='voucher_no',
            field=models.CharField(blank=True, help_text='Sequential Journal Voucher number for statutory audit trail. Format: {COMPANY}-JV-{FY}-{NNNN}, resets per fiscal year.', max_length=60, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='journalentryline',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
        migrations.AlterField(
            model_name='ledgeropeningbalance',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
        migrations.AlterField(
            model_name='tdsdeduction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
        migrations.RunPython(_recreate_views, migrations.RunPython.noop),
    ]
