# Generated by Django 6.0.4 on 2026-08-11 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0030_fn_invoice_journal_merged_fix'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journalentryline',
            name='is_reconciled',
        ),
        migrations.RemoveField(
            model_name='journalentryline',
            name='reconciled_date',
        ),
        migrations.AlterField(
            model_name='journalentryline',
            name='cleared_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
