# Generated by Django 6.0.4 on 2026-10-01 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0030_journalentry_fiscal_year_journalentry_voucher_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='source_type',
            field=models.CharField(choices=[('SALES_INVOICE', 'Sales Invoice'), ('CREDIT_NOTE', 'Credit Note'), ('DEBIT_NOTE', 'Debit Note'), ('VENDOR_BILL', 'Vendor Bill'), ('PAYMENT', 'Payment'), ('EXPENSE', 'Expense'), ('PAYROLL', 'Payroll'), ('DEPRECIATION', 'Depreciation'), ('STOCK_DISPOSAL', 'Stock Disposal'), ('OPENING_BALANCE', 'Opening Balance'), ('CLOSING_ENTRY', 'Year-End Closing'), ('MANUAL_JOURNAL', 'Manual Journal Voucher'), ('REVERSAL', 'Reversal'), ('BAD_DEBT_WRITEOFF', 'Bad Debt Write-off'), ('DOUBTFUL_DEBT_PROVISION', 'Provision for Doubtful Debts'), ('ACCRUED_EXPENSE', 'Accrued Expense'), ('PREPAID_AMORTIZATION', 'Prepaid Expense Amortization'), ('FX_ADJUSTMENT', 'Foreign Exchange Gain/Loss'), ('TAX_PROVISION', 'Income Tax Provision'), ('CLOSING_STOCK', 'Closing Stock Adjustment'), ('COGS', 'Cost of Goods Sold'), ('GRN', 'Goods Received (GRNI)'), ('OTHER', 'Other')], default='OTHER', help_text='Categorises the entry for filtering/reporting (Journal Voucher Register, etc.).', max_length=30),
        ),
    ]
