# Generated by Django 6.0.4 on 2026-08-03 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_room_roombooking_roomcharge_roomtype_room_room_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printerstation',
            name='printer_type',
            field=models.CharField(choices=[('KOT', 'Kitchen Order Ticket (KOT)'), ('BOT', 'Bar Order Ticket (BOT)'), ('BILL', 'Bill / Receipt Printer'), ('RECEIPT', 'POS Receipt Printer'), ('INVOICE', 'Invoice Printer'), ('LABEL', 'Barcode / Label Printer')], max_length=10),
        ),
        migrations.AlterField(
            model_name='printjob',
            name='job_type',
            field=models.CharField(choices=[('KOT', 'Kitchen Order Ticket (KOT)'), ('BOT', 'Bar Order Ticket (BOT)'), ('BILL', 'Bill / Receipt Printer'), ('RECEIPT', 'POS Receipt Printer'), ('INVOICE', 'Invoice Printer'), ('LABEL', 'Barcode / Label Printer')], max_length=10),
        ),
    ]
