# Generated by Django 6.0.4 on 2026-08-03 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_alter_printerstation_printer_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='printerstation',
            name='connection_type',
            field=models.CharField(choices=[('NETWORK', 'Network (IP address)'), ('LOCAL', 'Local / USB (this computer)')], default='NETWORK', max_length=10),
        ),
        migrations.AddField(
            model_name='printerstation',
            name='local_printer_name',
            field=models.CharField(blank=True, help_text='Exact name of the printer as registered on this computer\'s OS print system (e.g. "EPSON TM-T88").', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='printerstation',
            name='name',
            field=models.CharField(help_text='e.g. "Kitchen Printer", "Counter Receipt Printer"', max_length=100),
        ),
    ]
