# Generated by Django 6.0.4 on 2026-04-29 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_alter_invoice_sequence_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='hscode',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='HS Code'),
        ),
        migrations.AddField(
            model_name='vendorbillitem',
            name='hscode',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='HS Code'),
        ),
    ]
