# Generated by Django 6.0.4 on 2026-05-29 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0015_cbmssubmission'),
        ('company', '0012_company_cbms_password_company_cbms_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorbill',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Branch this bill was recorded at (optional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_bills', to='company.branch'),
        ),
        migrations.AddField(
            model_name='vendorbill',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Company this bill belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendor_bills', to='company.company'),
        ),
    ]
