# Generated by Django 6.0.4 on 2026-06-04 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0018_vendorbill_total_amount_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('ISSUED', 'Issued'), ('ESTIMATE', 'Estimate'), ('CANCELLED', 'Cancelled')], default='DRAFT', help_text='DRAFT = editable; ISSUED = locked; CANCELLED = voided.', max_length=10),
        ),
    ]
