# Generated by Django 6.0.4 on 2026-07-06 08:26

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0025_vendorbill_tax_amount_vendorbill_tax_percent'),
        ('vendors', '0006_vendor_vat_registered'),
    ]

    operations = [
        migrations.AddField(
            model_name='debitnote',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='debit_notes', to='vendors.vendor'),
        ),
        migrations.AddField(
            model_name='debitnote',
            name='vendor_bill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='debit_notes', to='billing.vendorbill'),
        ),
        migrations.AlterField(
            model_name='creditnote',
            name='status',
            field=models.CharField(choices=[('ISSUED', 'Issued'), ('APPLIED', 'Applied'), ('CANCELLED', 'Cancelled')], default='ISSUED', max_length=10),
        ),
        migrations.AlterField(
            model_name='debitnote',
            name='status',
            field=models.CharField(choices=[('ISSUED', 'Issued'), ('APPLIED', 'Applied'), ('CANCELLED', 'Cancelled')], default='ISSUED', max_length=10),
        ),
        migrations.AlterField(
            model_name='debitnote',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='VAT/tax portion of this note. Pro-rated from the linked vendor bill when available.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('ISSUED', 'Issued'), ('ESTIMATE', 'Estimate'), ('CANCELLED', 'Cancelled')], default='ISSUED', help_text='ISSUED = locked; ESTIMATE = no journal; CANCELLED = voided.', max_length=10),
        ),
    ]
