# Generated by Django 6.0.4 on 2026-07-06 08:26
# Replaces 0026_debitnote_vendor_debitnote_vendor_bill_and_more: that migration
# duplicated the vendor/vendor_bill AddField ops already applied by the sibling
# 0026_debitnote_vendor_debitnote_vendor_bill (same migration number, two
# independently-generated branches), and duplicated the creditnote/debitnote
# status AlterField already reapplied by 0030_alter_creditnote_status_alter_debitnote_status.
# Only the two non-duplicate ops survive here.

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0027_alter_creditnote_status_alter_debitnote_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debitnote',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='VAT/tax portion of this note. Pro-rated from the linked vendor bill when available.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('ISSUED', 'Issued'), ('ESTIMATE', 'Estimate'), ('CANCELLED', 'Cancelled')], default='ISSUED', help_text='ISSUED = locked; ESTIMATE = no journal; CANCELLED = voided.', max_length=10),
        ),
    ]
