# Generated by Django 6.0.4 on 2026-07-06 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0025_vendorbill_tax_amount_vendorbill_tax_percent'),
        ('vendors', '0006_vendor_vat_registered'),
    ]

    operations = [
        migrations.AddField(
            model_name='debitnote',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='debit_notes', to='vendors.vendor'),
        ),
        migrations.AddField(
            model_name='debitnote',
            name='vendor_bill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='debit_notes', to='billing.vendorbill'),
        ),
    ]
