# Generated by Django 6.0.4 on 2026-07-06 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0026_debitnote_vendor_debitnote_vendor_bill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditnote',
            name='status',
            field=models.CharField(choices=[('APPLIED', 'Applied'), ('CANCELLED', 'Cancelled')], default='APPLIED', max_length=10),
        ),
        migrations.AlterField(
            model_name='debitnote',
            name='status',
            field=models.CharField(choices=[('APPLIED', 'Applied'), ('CANCELLED', 'Cancelled')], default='APPLIED', max_length=10),
        ),
    ]
