# Generated by Django 6.0.4 on 2026-07-20 06:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0027_migrate_draft_statuses'),
        ('bookkeeping', '0018_fn_invoice_journal_soft_delete'),
        ('company', '0013_company_cit_rate'),
        ('customers', '0005_customer_ref_by'),
        ('vendors', '0006_vendor_vat_registered'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='creditnote',
            name='fiscal_year',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_notes', to='company.fiscalyear'),
        ),
        migrations.AddField(
            model_name='creditnote',
            name='sequence_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='debitnote',
            name='fiscal_year',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='debit_notes', to='company.fiscalyear'),
        ),
        migrations.AddField(
            model_name='debitnote',
            name='sequence_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='creditnote',
            constraint=models.UniqueConstraint(condition=models.Q(('sequence_number__isnull', False)), fields=('company', 'fiscal_year', 'sequence_number'), name='unique_credit_note_seq_per_company_fy'),
        ),
        migrations.AddConstraint(
            model_name='debitnote',
            constraint=models.UniqueConstraint(condition=models.Q(('sequence_number__isnull', False)), fields=('company', 'fiscal_year', 'sequence_number'), name='unique_debit_note_seq_per_company_fy'),
        ),
    ]
