# Generated by Django 6.0.4 on 2026-07-21 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0027_alter_creditnote_status_alter_debitnote_status'),
        ('billing', '0028_creditnote_fiscal_year_creditnote_sequence_number_and_more'),
    ]

    operations = [
    ]
