# Generated by Django 6.0.4 on 2026-07-31 07:22

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0029_alter_invoice_status_baddebtwriteoff'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='delivery_charge',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Delivery/shipping fee charged to the customer. Posted to the Delivery Income ledger account, separate from Sales Revenue.', max_digits=10),
        ),
    ]
