# Generated by Django 6.0.4 on 2026-08-18 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0030_invoice_delivery_charge'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorbill',
            name='tds_category',
            field=models.CharField(blank=True, choices=[('RENT', 'Rent'), ('SERVICE_FEE', 'Service Fee'), ('CONTRACT', 'Contract Payment'), ('COMMISSION', 'Commission'), ('PROFESSIONAL_FEE', 'Professional Fee'), ('OTHER', 'Other')], help_text='Nepal withholding tax category. Blank = no TDS applies to this bill.', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('ISSUED', 'Issued'), ('ESTIMATE', 'Estimate'), ('CANCELLED', 'Cancelled'), ('WRITTEN_OFF', 'Written Off')], default='ISSUED', help_text='ISSUED = locked; ESTIMATE = non-VAT sale (still journalised); CANCELLED = voided.', max_length=11),
        ),
    ]
