# Generated by Django 6.0.4 on 2026-09-22 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0031_vendorbill_tds_category_alter_invoice_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='unit_cost',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='NFRS 2: actual per-unit cost consumed at sale time (FIFO lot cost, or weighted-average cost_price). Null on rows created before this field existed, or where cost was not tracked at sale time — COGS reports fall back to product.cost_price for those.', max_digits=12, null=True),
        ),
    ]
