# Generated by Django 6.0.4 on 2026-08-11 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0032_invoice_delivery_charge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('ISSUED', 'Issued'), ('ESTIMATE', 'Estimate'), ('CANCELLED', 'Cancelled'), ('WRITTEN_OFF', 'Written Off')], default='ISSUED', help_text='ISSUED = locked; ESTIMATE = non-VAT sale (still journalised); CANCELLED = voided.', max_length=11),
        ),
    ]
