# Generated by Django 6.0.4 on 2026-10-01 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0032_invoiceitem_unit_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='stock_issued_at',
            field=models.DateTimeField(blank=True, editable=False, help_text='Set once stock was deducted and COGS posted for this invoice (idempotency marker).', null=True),
        ),
    ]
