# Generated by Django 6.0.4 on 2026-08-19 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0033_alter_invoice_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorbill',
            name='tds_category',
            field=models.CharField(blank=True, choices=[('RENT', 'Rent'), ('SERVICE_FEE', 'Service Fee'), ('CONTRACT', 'Contract Payment'), ('COMMISSION', 'Commission'), ('PROFESSIONAL_FEE', 'Professional Fee'), ('OTHER', 'Other')], help_text='Nepal withholding tax category. Blank = no TDS applies to this bill.', max_length=20, null=True),
        ),
    ]
