# Generated by Django 6.0.4 on 2026-05-16 17:12

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0010_initial'),
        ('tours', '0002_iata_ticketing'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIRFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('file', models.FileField(blank=True, null=True, upload_to='air_files/%Y/%m/')),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('period_from', models.DateField(help_text='BSP billing period start')),
                ('period_to', models.DateField(help_text='BSP billing period end')),
                ('billing_reference', models.CharField(blank=True, help_text='BSP billing reference / remittance ID', max_length=100)),
                ('total_sales', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total ticket sales gross amount', max_digits=14)),
                ('total_refunds', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Refunds / voids in this period', max_digits=14)),
                ('total_commission', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Commission earned on sales', max_digits=14)),
                ('total_taxes', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('net_amount_due', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Net payable to BSP (sales - refunds - commission)', max_digits=14)),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending Payment'), ('PARTIALLY_PAID', 'Partially Paid'), ('PAID', 'Paid'), ('DISPUTED', 'Disputed')], default='PENDING', max_length=20)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('payment_due_date', models.DateField(blank=True, help_text='BSP payment due date', null=True)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('notes', models.TextField(blank=True)),
                ('bsp_source_file', models.ForeignKey(blank=True, help_text='Link to the matching BSP billing file for ticket-level drill-down', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='air_files', to='tours.iatasourcefile')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='air_files', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-period_to'],
            },
        ),
        migrations.CreateModel(
            name='BSPPaymentRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('payment_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('payment_method', models.CharField(choices=[('BANK_TRANSFER', 'Bank Transfer'), ('CHEQUE', 'Cheque'), ('ONLINE', 'Online Payment'), ('OTHER', 'Other')], default='BANK_TRANSFER', max_length=20)),
                ('bank_reference', models.CharField(blank=True, help_text='Bank transaction / cheque reference', max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('air_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='tours.airfile')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['payment_date'],
            },
        ),
    ]
