# Generated by Django 6.0.4 on 2026-07-06 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_add_air_file_and_bsp_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourbooking',
            name='status',
            field=models.CharField(choices=[('CONFIRMED', 'Confirmed'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='CONFIRMED', max_length=20),
        ),
    ]
