# Generated by Django 6.0.4 on 2026-06-01 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0003_add_blog_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='herobanner',
            name='banner_type',
            field=models.CharField(choices=[('HERO', 'Hero Slider'), ('PROMO', 'Promo Box (right side)')], default='HERO', max_length=10),
        ),
    ]
