# Generated by Django 6.0.4 on 2026-06-05 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0004_add_banner_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='free_shipping_threshold',
            field=models.PositiveIntegerField(default=5000),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='show_special_offer',
            field=models.BooleanField(default=True, help_text='Show the Special Offer badge in header'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='show_topbar',
            field=models.BooleanField(default=True, help_text='Show the top announcement/info bar on storefront'),
        ),
    ]
