# Generated by Django 6.0.4 on 2026-06-05 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0005_add_sitesettings_display_flags'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='show_in_nav',
            field=models.BooleanField(default=False),
        ),
    ]
