# Generated by Django 6.0.4 on 2026-06-17 09:03

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0007_ecomorder_discount_amount_discountcoupon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecomorder',
            name='delivery_charge',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='delivery_charge',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Fixed delivery fee added at checkout. Set 0 to disable.', max_digits=10),
        ),
    ]
