# Generated by Django 6.0.4 on 2026-06-21 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0008_add_delivery_charge'),
        ('products', '0016_product_conversion_factor_product_has_variants_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecomorderitem',
            name='variant',
            field=models.ForeignKey(blank=True, help_text='Populated when ordering a size/color variant.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ecom_order_items', to='products.productvariant'),
        ),
    ]
