# Generated by Django 6.0.4 on 2026-08-11 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0013_alter_blogpost_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecomorder',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'Payment Pending'), ('PAID', 'Paid'), ('FAILED', 'Payment Failed')], default='PENDING', max_length=10),
        ),
        migrations.AlterField(
            model_name='ecomorder',
            name='payment_method',
            field=models.CharField(choices=[('COD', 'Cash on Delivery'), ('ONLINE', 'Paid Online')], default='COD', max_length=10),
        ),
    ]
