# Generated by Django 6.0.4 on 2026-09-22 13:17

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0014_ecomorder_fiscal_year_ecomorder_sequence_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecomorder',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AddField(
            model_name='ecomorder',
            name='tax_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
    ]
