# Generated by Django 5.2.3 on 2025-06-30 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_alter_invoice_status_alter_vendorbill_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='status',
        ),
        migrations.AddField(
            model_name='invoice',
            name='due_date_bs',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
