# Generated by Django 5.2.3 on 2025-06-30 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_remove_invoice_status_invoice_due_date_bs'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='sequence_number',
            field=models.PositiveIntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
