# Generated by GitHub Copilot
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0010_remove_invoice_branch_remove_vendorbill_branch'),
        ('company', '0006_company_organisation_type_vat'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='branch',
            field=models.ForeignKey(
                'company.Branch',
                on_delete=django.db.models.deletion.SET_NULL,
                null=True,
                blank=True,
                related_name='invoices',
                help_text='Branch this invoice was raised from (optional).',
            ),
        ),
    ]
