# Generated by Django 6.0.4 on 2026-06-01 07:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0016_vendorbill_branch_vendorbill_company'),
        ('company', '0013_company_cit_rate'),
        ('customers', '0004_phone_null_unique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['company', 'status', 'outstanding_balance'], name='invoice_company_status_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['company', 'transaction_date'], name='invoice_company_date_idx'),
        ),
    ]
