# Generated by Django 6.0.4 on 2026-06-05 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0019_payment_numbering_and_vendor_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='sequence_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
