from django.urls import path
from . import views

app_name = 'reports'

urlpatterns = [
    path('', views.report_dashboard, name='report_dashboard'),
    path('trial-balance/', views.trial_balance_report,
         name='trial_balance_report'),
    path('balance-sheet/', views.balance_sheet_report,
         name='balance_sheet_report'),
    path('balance-sheet/export/excel/', views.export_balance_sheet_report_excel,
         name='export_balance_sheet_report_excel'),
    path('balance-sheet/export/pdf/', views.export_balance_sheet_report_pdf,
         name='export_balance_sheet_report_pdf'),
    path('balance-sheet/print/', views.print_balance_sheet_report,
         name='print_balance_sheet_report'),
    path('profit-and-loss/', views.profit_and_loss_report,
         name='profit_and_loss_report'),
    path('cash-flow/', views.cash_flow_report, name='cash_flow_report'),
    path('sales/detailed/', views.detailed_sales_report,
         name='detailed_sales_report'),
    path('sales/by-user/', views.sales_by_user_report,
         name='sales_by_user_report'),
    path('sales/by-user/export/excel/', views.export_sales_by_user_report_excel,
         name='export_sales_by_user_report_excel'),
    path('sales/by-user/export/pdf/', views.export_sales_by_user_report_pdf,
         name='export_sales_by_user_report_pdf'),
    path('sales/by-user/print/', views.print_sales_by_user_report,
         name='print_sales_by_user_report'),
    path('sales/referrals/', views.referral_report, name='referral_report'),
    path('products/performance/', views.product_performance_report,
         name='product_performance_report'),
    path('products/performance/export/excel/', views.export_product_performance_report_excel,
         name='export_product_performance_report_excel'),
    path('products/performance/export/pdf/', views.export_product_performance_report_pdf,
         name='export_product_performance_report_pdf'),
    path('products/performance/print/', views.print_product_performance_report,
         name='print_product_performance_report'),
    path('products/sales/', views.product_sales_report,
         name='product_sales_report'),
    path('services/sales/', views.service_sales_report,
         name='service_sales_report'),
    path('sales/by-customer/', views.sales_by_customer_report,
         name='sales_by_customer_report'),
    path('revenue/by-time/', views.revenue_by_time_report,
         name='revenue_by_time_report'),
    path('invoices/outstanding/', views.outstanding_invoices_report,
         name='outstanding_invoices_report'),
    path('invoices/outstanding/export/excel/', views.export_outstanding_invoices_report_excel,
         name='export_outstanding_invoices_report_excel'),
    path('invoices/outstanding/export/pdf/', views.export_outstanding_invoices_report_pdf,
         name='export_outstanding_invoices_report_pdf'),
    path('invoices/outstanding/print/', views.print_outstanding_invoices_report,
         name='print_outstanding_invoices_report'),
    path('payments/history/', views.payment_history_report,
         name='payment_history_report'),
    path('payments/history/export/excel/', views.export_payment_history_report_excel,
         name='export_payment_history_report_excel'),
    path('payments/history/export/pdf/', views.export_payment_history_report_pdf,
         name='export_payment_history_report_pdf'),
    path('payments/history/print/', views.print_payment_history_report,
         name='print_payment_history_report'),
    path('notes/debit-credit/', views.debit_credit_note_report,
         name='debit_credit_note_report'),
    path('ar-aging/', views.ar_aging_report, name='ar_aging_report'),
    path('sales/by-category/', views.sales_by_category_report,
         name='sales_by_category_report'),
    path('sales/by-category/export/excel/', views.export_sales_by_category_report_excel,
         name='export_sales_by_category_report_excel'),
    path('sales/by-category/export/pdf/', views.export_sales_by_category_report_pdf,
         name='export_sales_by_category_report_pdf'),
    path('sales/by-category/print/', views.print_sales_by_category_report,
         name='print_sales_by_category_report'),
    path('billing/cogs/', views.cogs_report, name='cogs_report'),
    path('billing/cogs/export/excel/', views.export_cogs_report_excel,
         name='export_cogs_report_excel'),
    path('billing/cogs/export/pdf/', views.export_cogs_report_pdf,
         name='export_cogs_report_pdf'),
    path('billing/cogs/print/', views.print_cogs_report,
         name='print_cogs_report'),
    path('billing/profitability/', views.profitability_report,
         name='profitability_report'),
    path('products/inventory/', views.inventory_report, name='inventory_report'),
    path('products/stock-movement/', views.stock_movement_report,
         name='stock_movement_report'),
    path('products/stock-movement/export/excel/',
         views.export_stock_movement_report_excel, name='export_stock_movement_report_excel'),
    path('products/stock-movement/export/pdf/',
         views.export_stock_movement_report_pdf, name='export_stock_movement_report_pdf'),
    path('products/stock-movement/print/',
         views.print_stock_movement_report, name='print_stock_movement_report'),
    path('customers/acquisition/', views.customer_acquisition_report,
         name='customer_acquisition_report'),
    path('purchasing/purchase-order-list/',
         views.purchase_order_list_report, name='purchase_order_list_report'),
    path('purchasing/vendor-payment-list/',
         views.vendor_payment_list_report, name='vendor_payment_list_report'),
    path('bookkeeping/ledger-accounts/', views.ledger_account_list_report,
         name='ledger_account_list_report'),
    path('bookkeeping/payment-list/',
         views.payment_list_report, name='payment_list_report'),
    path('bookkeeping/payment-list/export/excel/',
         views.export_payment_list_excel, name='export_payment_list_excel'),
    path('bookkeeping/payment-list/export/pdf/',
         views.export_payment_list_pdf, name='export_payment_list_pdf'),
    path('bookkeeping/payment-list/print/',
         views.print_payment_list_report, name='print_payment_list_report'),
    path('bookkeeping/journal-entries/', views.journal_entry_list_report,
         name='journal_entry_list_report'),
    path('billing/profitability/export/excel/', views.export_profit_and_loss_report_excel,
         name='export_profit_and_loss_report_excel'),
    path('billing/profitability/export/pdf/', views.export_profit_and_loss_report_pdf,
         name='export_profit_and_loss_report_pdf'),
    path('billing/profitability/print/', views.print_profit_and_loss_report,
         name='print_profit_and_loss_report'),
    # Purchasing Reports
    path('purchasing/vendor-list/export/pdf/',
         views.export_vendor_list_report_pdf, name='export_vendor_list_report_pdf'),
    path('purchasing/vendor-list/print/', views.print_vendor_list_report,
         name='print_vendor_list_report'),
    path('purchasing/purchase-order-list/export/excel/',
         views.export_purchase_order_list_report_excel, name='export_purchase_order_list_report_excel'),
    path('purchasing/purchase-order-list/export/pdf/',
         views.export_purchase_order_list_report_pdf, name='export_purchase_order_list_report_pdf'),
    path('purchasing/purchase-order-list/print/',
         views.print_purchase_order_list_report, name='print_purchase_order_list_report'),
    path('purchasing/vendor-bill-list/', views.vendor_bill_list_report,
         name='vendor_bill_list_report'),
    path('purchasing/vendor-bill-list/export/excel/',
         views.export_vendor_bill_list_report_excel, name='export_vendor_bill_list_report_excel'),
    path('purchasing/vendor-bill-list/export/pdf/',
         views.export_vendor_bill_list_report_pdf, name='export_vendor_bill_list_report_pdf'),
    path('purchasing/vendor-bill-list/print/',
         views.print_vendor_bill_list_report, name='print_vendor_bill_list_report'),
    path('purchasing/vendor-payment-list/export/excel/',
         views.export_vendor_payment_list_report_excel, name='export_vendor_payment_list_report_excel'),
    path('purchasing/vendor-payment-list/export/pdf/',
         views.export_vendor_payment_list_report_pdf, name='export_vendor_payment_list_report_pdf'),
    path('purchasing/vendor-payment-list/print/',
         views.print_vendor_payment_list_report, name='print_vendor_payment_list_report'),
    # Customer Reports
    path('customers/acquisition/export/excel/', views.export_customer_acquisition_report_excel,
         name='export_customer_acquisition_report_excel'),
    path('customers/acquisition/export/pdf/', views.export_customer_acquisition_report_pdf,
         name='export_customer_acquisition_report_pdf'),
    path('customers/acquisition/print/', views.print_customer_acquisition_report,
         name='print_customer_acquisition_report'),
    path('fiscal-year-dashboard/', views.fiscal_year_dashboard,
         name='fiscal_year_dashboard'),
    path('fiscal-year-dashboard/export/csv/', views.export_fiscal_year_dashboard_csv,
         name='export_fiscal_year_dashboard_csv'),
    path('fiscal-year-dashboard/export/excel/', views.export_fiscal_year_dashboard_excel,
         name='export_fiscal_year_dashboard_excel'),

    # ── New reports ──────────────────────────────────────────────────────────
    path('financial/ratio-analysis/', views.ratio_analysis_report,
         name='ratio_analysis_report'),
    path('financial/ratio-analysis/export/excel/', views.export_ratio_analysis_excel,
         name='export_ratio_analysis_excel'),
    path('financial/ratio-analysis/print/', views.print_ratio_analysis_report,
         name='print_ratio_analysis_report'),

    path('financial/ap-aging/', views.ap_aging_report,
         name='ap_aging_report'),
    path('financial/ap-aging/export/excel/', views.export_ap_aging_excel,
         name='export_ap_aging_excel'),

    path('financial/tax-report/', views.tax_report,
         name='tax_report'),
    path('financial/tax-report/export/excel/', views.export_tax_report_excel,
         name='export_tax_report_excel'),
    path('financial/tax-report/print/', views.print_tax_report,
         name='print_tax_report'),

    path('financial/cash-position/', views.cash_position_report,
         name='cash_position_report'),
    path('financial/cash-position/export/excel/', views.export_cash_position_excel,
         name='export_cash_position_excel'),

    path('hr/payroll-summary/', views.payroll_summary_report,
         name='payroll_summary_report'),
    path('hr/payroll-summary/export/excel/', views.export_payroll_summary_excel,
         name='export_payroll_summary_excel'),
    path('hr/payroll-summary/print/', views.print_payroll_summary_report,
         name='print_payroll_summary_report'),

    # VAT Period Report (monthly / 4-monthly / bi-yearly)
    path('financial/vat-period/', views.vat_period_report,
         name='vat_period_report'),
    path('financial/vat-period/export/excel/', views.export_vat_period_report_excel,
         name='export_vat_period_report_excel'),
    path('financial/vat-period/print/', views.print_vat_period_report,
         name='print_vat_period_report'),

    # NFRS 1 — Statement of Changes in Equity
    path('financial/changes-in-equity/', views.changes_in_equity_report,
         name='changes_in_equity_report'),

    # NFRS 13 — Fixed Asset Register
    path('financial/fixed-assets/', views.fixed_asset_register_report,
         name='fixed_asset_register_report'),

    # ── Vendor-wise Inventory Report ──────────────────────────────────────
    path('products/inventory/by-vendor/', views.vendor_wise_inventory_report,
         name='vendor_wise_inventory_report'),
    path('products/inventory/by-vendor/export/excel/', views.export_vendor_wise_inventory_excel,
         name='export_vendor_wise_inventory_excel'),

    # ── Sales by Reference Number Report ──────────────────────────────────
    path('sales/by-reference/', views.sales_by_reference_report,
         name='sales_by_reference_report'),
    path('sales/by-reference/export/excel/', views.export_sales_by_reference_excel,
         name='export_sales_by_reference_excel'),

    # ── Purchase Price History Report ─────────────────────────────────────
    path('products/purchase-price-history/', views.purchase_price_history_report,
         name='purchase_price_history_report'),
    path('products/purchase-price-history/export/excel/', views.export_purchase_price_history_excel,
         name='export_purchase_price_history_excel'),

    # ── Report Access Management (company admin only) ─────────────────────
    path('access/', views.report_access_manage, name='report_access_manage'),
    path('access/<uuid:user_pk>/toggle/', views.report_access_toggle, name='report_access_toggle'),
    path('access/<uuid:user_pk>/bulk/', views.report_access_bulk, name='report_access_bulk'),
]
