# Generated by Django 6.0.4 on 2026-06-04 12:05

from django.conf import settings
from django.db import migrations, models


def nullify_duplicate_payment_references(apps, schema_editor):
    """
    Before adding the uniqueness constraint, NULL-out any duplicate
    reference_number values within the same company so the constraint
    can be created cleanly.  Duplicates are a data-quality issue from
    the old non-atomic numbering service; nullifying them is safe because
    payment_number falls back to invoice number or PAY-<id>.
    """
    Payment = apps.get_model('payments', 'Payment')
    db_alias = schema_editor.connection.alias

    seen = set()
    for p in (
        Payment.objects.using(db_alias)
        .exclude(reference_number__isnull=True)
        .order_by('date', 'created_at')
        .values('id', 'company_id', 'reference_number')
    ):
        key = (str(p['company_id']), p['reference_number'])
        if key in seen:
            Payment.objects.using(db_alias).filter(pk=p['id']).update(
                reference_number=None,
                sequence_number=None,
            )
        else:
            seen.add(key)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0019_payment_numbering_and_vendor_ref'),
        ('bookkeeping', '0014_journal_entry_reversal_fields'),
        ('company', '0013_company_cit_rate'),
        ('payments', '0008_alter_expense_journal_entry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-date', '-created_at']},
        ),
        migrations.AddField(
            model_name='vendorpayment',
            name='reference_number',
            field=models.CharField(blank=True, help_text='Auto-generated vendor payment number (VPY-...)', max_length=100, null=True),
        ),
        # Deduplicate before adding the unique constraint
        migrations.RunPython(nullify_duplicate_payment_references, reverse_code=noop),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('reference_number__isnull', False)), fields=('company', 'reference_number'), name='unique_payment_reference_per_company'),
        ),
    ]
