# Generated by Django 6.0.4 on 2026-06-04 13:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0013_company_cit_rate'),
        ('hrpayroll', '0002_extend_employee_and_new_hr_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='company.company'),
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='run_number',
            field=models.CharField(blank=True, help_text='Auto-generated sequential run number, e.g. PR-2081-001', max_length=30),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='unique_department_name_per_company'),
        ),
        migrations.AddConstraint(
            model_name='payrollrun',
            constraint=models.UniqueConstraint(condition=models.Q(('run_number__gt', '')), fields=('company', 'run_number'), name='unique_payroll_run_number_per_company'),
        ),
    ]
