# Generated by Django 6.0.4 on 2026-07-06 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrpayroll', '0003_department_company_payrollrun_runnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performancereview',
            name='status',
            field=models.CharField(choices=[('SUBMITTED', 'Submitted'), ('ACKNOWLEDGED', 'Acknowledged')], default='SUBMITTED', max_length=15),
        ),
    ]
