# Generated by Django 6.0.4 on 2026-08-11 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0016_company_receipt_footer_text'),
        ('hrpayroll', '0004_alter_performancereview_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollrun',
            name='fiscal_year',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_runs', to='company.fiscalyear'),
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='sequence_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payrollrun',
            name='run_number',
            field=models.CharField(blank=True, help_text='Auto-generated sequential run number, e.g. DPS-PR-2082/83-001', max_length=30),
        ),
    ]
