# Generated by Django 5.2.3 on 2025-07-13 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_add_payment_type_and_ledger_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='reference_number',
            field=models.CharField(blank=True, help_text='Payment/Bill number', max_length=100, null=True),
        ),
    ]
