# Generated by Django 6.0.4 on 2026-06-04 12:08

from django.conf import settings
from django.db import migrations, models


def nullify_duplicate_expense_references(apps, schema_editor):
    """
    NULL/empty-out duplicate Expense.reference_number values per company
    before the unique constraint is applied.
    """
    Expense = apps.get_model('payments', 'Expense')
    db_alias = schema_editor.connection.alias

    seen = set()
    for e in (
        Expense.objects.using(db_alias)
        .exclude(reference_number__isnull=True)
        .exclude(reference_number='')
        .order_by('date', 'created_at')
        .values('id', 'company_id', 'reference_number')
    ):
        key = (str(e['company_id']), e['reference_number'])
        if key in seen:
            Expense.objects.using(db_alias).filter(pk=e['id']).update(reference_number=None)
        else:
            seen.add(key)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0014_journal_entry_reversal_fields'),
        ('company', '0013_company_cit_rate'),
        ('payments', '0009_payment_numbering_and_vendor_ref'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(nullify_duplicate_expense_references, reverse_code=noop),
        migrations.AddConstraint(
            model_name='expense',
            constraint=models.UniqueConstraint(condition=models.Q(('reference_number__isnull', False), models.Q(('reference_number', ''), _negated=True)), fields=('company', 'reference_number'), name='unique_expense_reference_per_company'),
        ),
    ]
