# Generated by Django 6.0.4 on 2026-08-19 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0013_bankreconciliation'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankreconciliation',
            name='bank_charges_not_recorded',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Bank charges/fees on the statement not yet recorded in the books.', max_digits=14),
        ),
        migrations.AddField(
            model_name='bankreconciliation',
            name='deposits_in_transit',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Deposits recorded in books but not yet reflected on the bank statement.', max_digits=14),
        ),
        migrations.AddField(
            model_name='bankreconciliation',
            name='interest_not_recorded',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Interest or other bank credits on the statement not yet recorded in the books.', max_digits=14),
        ),
        migrations.AddField(
            model_name='bankreconciliation',
            name='other_adjustments',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Any other net reconciling adjustment to the book balance (can be negative).', max_digits=14),
        ),
        migrations.AddField(
            model_name='bankreconciliation',
            name='unpresented_cheques',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cheques issued and recorded in books but not yet cleared by the bank.', max_digits=14),
        ),
    ]
