# Generated by Django 5.2.3 on 2025-06-30 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiscalyear',
            name='end_date_bs',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fiscalyear',
            name='start_date_bs',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
