# Generated by Django 5.2.3 on 2025-06-30 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_fiscalyear_end_date_bs_fiscalyear_start_date_bs'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiscalyear',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
