# Generated by Django 5.2.3 on 2025-07-02 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_fiscalyear_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiscalyear',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
