# Generated by Django 6.0.4 on 2026-04-29 17:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_fiscalyear_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fiscalyear',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fiscalyear',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_fiscal_years', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fiscalyear',
            name='is_closed',
            field=models.BooleanField(default=False, help_text='Closed years are read-only. No new transactions allowed.'),
        ),
    ]
