# Generated by Django 6.0.4 on 2026-05-03 04:12

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_company_order_manufacturing_flags'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='enable_hr_payroll',
            field=models.BooleanField(default=True, help_text='Enable HR & Payroll module (Employees, Attendance, Payroll Runs).'),
        ),
        migrations.AddField(
            model_name='company',
            name='enable_inventory',
            field=models.BooleanField(default=True, help_text='Enable Inventory / Product management module.'),
        ),
        migrations.AddField(
            model_name='company',
            name='enable_purchasing',
            field=models.BooleanField(default=True, help_text='Enable Purchasing module (Purchase Orders, Vendor Bills).'),
        ),
        migrations.AddField(
            model_name='company',
            name='enable_restaurant',
            field=models.BooleanField(default=False, help_text='Enable Restaurant module (Tables, KOT/BOT, Dining Orders, Printer Stations).'),
        ),
        migrations.AlterField(
            model_name='company',
            name='enable_project_tracking',
            field=models.BooleanField(default=False, help_text='Enable project / cost-centre module.'),
        ),
        migrations.AlterField(
            model_name='company',
            name='organisation_type',
            field=models.CharField(choices=[('TRADING', 'Trading / Retail'), ('SERVICE', 'Service'), ('PROJECT', 'Project-Based'), ('NGO', 'NGO / Non-Profit'), ('MANUFACTURING', 'Manufacturing'), ('RESTAURANT', 'Restaurant / F&B'), ('SMALL_ENTERPRISE', 'Small Enterprise'), ('OTHER', 'Other')], default='TRADING', help_text='Nature of the organisation — drives which modules are available.', max_length=20),
        ),
        migrations.AlterField(
            model_name='company',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('13.00'), help_text='Default VAT/tax rate for this company (e.g., 13.00 for 13%)', max_digits=5),
        ),
    ]
