# Generated by Django 6.0.4 on 2026-05-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_extend_employee_and_new_hr_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='enable_pos',
            field=models.BooleanField(
                default=False,
                help_text='Enable Point of Sale (POS) module for quick retail/counter sales.'
            ),
        ),
    ]
