# Generated by Django 6.0.4 on 2026-05-16 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_company_enable_pos'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='enable_tours',
            field=models.BooleanField(default=False, help_text='Enable Tours & Ticketing module (Enquiries, Bookings, Invoicing).'),
        ),
        migrations.AlterField(
            model_name='company',
            name='organisation_type',
            field=models.CharField(choices=[('TRADING', 'Trading / Retail'), ('SERVICE', 'Service'), ('PROJECT', 'Project-Based'), ('NGO', 'NGO / Non-Profit'), ('MANUFACTURING', 'Manufacturing'), ('RESTAURANT', 'Restaurant / F&B'), ('SMALL_ENTERPRISE', 'Small Enterprise'), ('TOUR_OPERATOR', 'Tour & Ticketing Operator'), ('OTHER', 'Other')], default='TRADING', help_text='Nature of the organisation — drives which modules are available.', max_length=20),
        ),
    ]
