# Generated by Django 6.0.4 on 2026-05-23 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0010_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='enable_ecom',
            field=models.BooleanField(default=False, help_text='Enable E-Commerce storefront (/store/). Customers can browse products and place COD orders online.'),
        ),
    ]
