# Generated by Django 6.0.4 on 2026-05-29 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0011_add_enable_ecom'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='cbms_password',
            field=models.CharField(blank=True, help_text='IRD Taxpayer Login Password for CBMS API.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='cbms_username',
            field=models.CharField(blank=True, help_text='IRD Taxpayer Login UserID for CBMS API.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='enable_ebilling',
            field=models.BooleanField(default=False, help_text='Enable real-time bill submission to Nepal IRD CBMS. Requires vat_number, cbms_username, and cbms_password.'),
        ),
    ]
