# Generated by Django 6.0.4 on 2026-05-29 16:55

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0012_company_cbms_password_company_cbms_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='cit_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('25.00'), help_text='NFRS 12: Corporate Income Tax rate (%). Nepal standard = 25%. Special industries may use 15%.', max_digits=5),
        ),
    ]
