# Generated by Django 6.0.4 on 2026-07-31 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0013_company_cit_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='invoice_print_format',
            field=models.CharField(choices=[('a4', 'A4'), ('thermal', 'Thermal (80mm)')], default='a4', help_text='Default print format for invoices.', max_length=10),
        ),
        migrations.AddField(
            model_name='company',
            name='pos_receipt_print_format',
            field=models.CharField(choices=[('a4', 'A4'), ('thermal', 'Thermal (80mm)')], default='thermal', help_text='Default print format for POS receipts.', max_length=10),
        ),
        migrations.AddField(
            model_name='company',
            name='sales_order_print_format',
            field=models.CharField(choices=[('a4', 'A4'), ('thermal', 'Thermal (80mm)')], default='a4', help_text='Default print format for sales order receipts.', max_length=10),
        ),
    ]
