# Generated by Django 6.0.4 on 2026-08-03 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0014_company_invoice_print_format_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='pan_number',
            field=models.CharField(blank=True, help_text='PAN registration number. Required for PAN-only firms; also set for VAT-registered firms (same number in Nepal).', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='vat_number',
            field=models.CharField(blank=True, help_text='VAT registration number (only applicable if VAT Registered is checked).', max_length=50, null=True),
        ),
    ]
