# Generated by Django 6.0.4 on 2026-08-03 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0015_company_pan_number_alter_company_vat_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='receipt_footer_text',
            field=models.CharField(blank=True, help_text='Shown at the bottom of POS receipts and invoices, e.g. "Goods once sold are not returned" or a thank-you message.', max_length=255, null=True),
        ),
    ]
