# Generated by Django 6.0.4 on 2026-08-18 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0016_company_receipt_footer_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='enable_ssf',
            field=models.BooleanField(default=False, help_text='Enable Social Security Fund (SSF) contributions on payroll. Explicit opt-in — not auto-enabled by organisation type.'),
        ),
    ]
