# Generated by Django 6.0.4 on 2026-08-18 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0017_company_enable_ssf'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='po_approval_threshold',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='POs at or above this amount require admin approval before being sent. Leave blank to skip PO approval entirely.', max_digits=12, null=True),
        ),
    ]
