# Generated by Django 6.0.4 on 2026-09-04 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0018_company_po_approval_threshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='store_domain',
            field=models.CharField(blank=True, help_text="Verified hostname for this company's storefront, e.g. shop.example.com.", max_length=255, null=True, unique=True),
        ),
    ]
