"""Initial migration for manufacturing app."""
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0006_company_organisation_type_vat'),
        ('orders', '0001_initial'),
        ('products', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
                ('machine_code', models.CharField(blank=True, max_length=50, null=True)),
                ('machine_type', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[
                    ('OPERATIONAL','Operational'),('MAINTENANCE','Under Maintenance'),
                    ('BREAKDOWN','Breakdown'),('IDLE','Idle'),('RETIRED','Retired')],
                    default='OPERATIONAL', max_length=15)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('last_maintenance_date', models.DateField(blank=True, null=True)),
                ('next_maintenance_date', models.DateField(blank=True, null=True)),
                ('hourly_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                    related_name='machines', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='created_machine', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='updated_machine', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='deleted_machine', to=settings.AUTH_USER_MODEL)),
            ],
            options={'ordering': ['name'],
                     'unique_together': {('company', 'machine_code')}},
        ),
        migrations.CreateModel(
            name='BillOfMaterials',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('version', models.CharField(default='v1', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('yield_quantity', models.DecimalField(decimal_places=3, default=Decimal('1.000'), max_digits=10)),
                ('yield_unit', models.CharField(default='pcs', max_length=20)),
                ('production_time_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                    related_name='boms', to='company.company')),
                ('finished_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                    related_name='boms', to='products.product')),
                ('created_by', models.ForeignKey(blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='created_bom', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='updated_bom', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='deleted_bom', to=settings.AUTH_USER_MODEL)),
            ],
            options={'ordering': ['finished_product__name', 'version'],
                     'unique_together': {('company', 'finished_product', 'version')}},
        ),
        migrations.CreateModel(
            name='BOMItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10)),
                ('unit', models.CharField(default='pcs', max_length=20)),
                ('scrap_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                    related_name='items', to='manufacturing.billofmaterials')),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                    related_name='used_in_boms', to='products.product')),
                ('created_by', models.ForeignKey(blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='created_bomitem', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='updated_bomitem', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='deleted_bomitem', to=settings.AUTH_USER_MODEL)),
            ],
            options={'ordering': ['raw_material__name'],
                     'unique_together': {('bom', 'raw_material')}},
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('work_order_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('status', models.CharField(choices=[
                    ('DRAFT','Draft'),('PLANNED','Planned'),('IN_PROGRESS','In Progress'),
                    ('COMPLETED','Completed'),('CANCELLED','Cancelled'),('ON_HOLD','On Hold')],
                    default='DRAFT', max_length=15)),
                ('planned_quantity', models.DecimalField(decimal_places=3, max_digits=10)),
                ('produced_quantity', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=10)),
                ('rejected_quantity', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=10)),
                ('planned_start_date', models.DateField(blank=True, null=True)),
                ('planned_end_date', models.DateField(blank=True, null=True)),
                ('actual_start_date', models.DateField(blank=True, null=True)),
                ('actual_end_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                    related_name='work_orders', to='company.company')),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                    related_name='work_orders', to='manufacturing.billofmaterials')),
                ('sales_order', models.ForeignKey(blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='work_orders', to='orders.salesorder')),
                ('cost_centre', models.ForeignKey(blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='work_orders', to='projects.costcentre')),
                ('created_by', models.ForeignKey(blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='created_workorder', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='updated_workorder', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='deleted_workorder', to=settings.AUTH_USER_MODEL)),
            ],
            options={'ordering': ['-planned_start_date', '-created_at']},
        ),
        migrations.CreateModel(
            name='WorkOrderMaterial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('quantity_planned', models.DecimalField(decimal_places=3, max_digits=10)),
                ('quantity_used', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=10)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                    related_name='material_consumption', to='manufacturing.workorder')),
                ('bom_item', models.ForeignKey(blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL, to='manufacturing.bomitem')),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                    related_name='consumed_in_production', to='products.product')),
                ('created_by', models.ForeignKey(blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='created_workordermaterial', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='updated_workordermaterial', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='deleted_workordermaterial', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductionRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('run_number', models.CharField(blank=True, max_length=50, null=True)),
                ('run_date', models.DateField(default=django.utils.timezone.now)),
                ('quantity_produced', models.DecimalField(decimal_places=3, max_digits=10)),
                ('quantity_rejected', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=10)),
                ('operator_name', models.CharField(blank=True, max_length=255, null=True)),
                ('shift', models.CharField(blank=True, choices=[
                    ('MORNING','Morning'),('AFTERNOON','Afternoon'),('NIGHT','Night')],
                    max_length=10, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                    related_name='production_runs', to='manufacturing.workorder')),
                ('machine', models.ForeignKey(blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='production_runs', to='manufacturing.machine')),
                ('created_by', models.ForeignKey(blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='created_productionrun', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='updated_productionrun', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='deleted_productionrun', to=settings.AUTH_USER_MODEL)),
            ],
            options={'ordering': ['-run_date', '-created_at']},
        ),
        migrations.CreateModel(
            name='QualityCheck',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('check_date', models.DateField(default=django.utils.timezone.now)),
                ('inspector_name', models.CharField(max_length=255)),
                ('result', models.CharField(choices=[
                    ('PASS','Pass'),('FAIL','Fail'),('PARTIAL','Partial Pass'),('PENDING','Pending')],
                    default='PENDING', max_length=10)),
                ('quantity_inspected', models.DecimalField(decimal_places=3, max_digits=10)),
                ('quantity_passed', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=10)),
                ('quantity_failed', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=10)),
                ('defect_description', models.TextField(blank=True, null=True)),
                ('corrective_action', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('production_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                    related_name='quality_checks', to='manufacturing.productionrun')),
                ('created_by', models.ForeignKey(blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='created_qualitycheck', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='updated_qualitycheck', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='deleted_qualitycheck', to=settings.AUTH_USER_MODEL)),
            ],
            options={'ordering': ['-check_date']},
        ),
        migrations.CreateModel(
            name='MachineLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('log_date', models.DateField(default=django.utils.timezone.now)),
                ('log_type', models.CharField(choices=[
                    ('USAGE','Usage'),('MAINTENANCE','Maintenance'),('BREAKDOWN','Breakdown'),
                    ('REPAIR','Repair'),('INSPECTION','Inspection')],
                    default='USAGE', max_length=15)),
                ('hours_used', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('description', models.TextField(blank=True, null=True)),
                ('technician_name', models.CharField(blank=True, max_length=255, null=True)),
                ('cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                    related_name='logs', to='manufacturing.machine')),
                ('created_by', models.ForeignKey(blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='created_machinelog', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='updated_machinelog', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='deleted_machinelog', to=settings.AUTH_USER_MODEL)),
            ],
            options={'ordering': ['-log_date']},
        ),
    ]
