# Generated by Django 6.0.4 on 2026-05-03 02:40

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0001_initial'),
        ('orders', '0002_alter_deliverynote_created_by_and_more'),
        ('products', '0003_product_hscode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='billofmaterials',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='billofmaterials',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='billofmaterials',
            name='finished_product',
            field=models.ForeignKey(help_text='The product this BOM produces.', on_delete=django.db.models.deletion.CASCADE, related_name='boms', to='products.product'),
        ),
        migrations.AlterField(
            model_name='billofmaterials',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='billofmaterials',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Only one active BOM per product.'),
        ),
        migrations.AlterField(
            model_name='billofmaterials',
            name='production_time_hours',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Estimated production time in hours.', max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='billofmaterials',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='billofmaterials',
            name='version',
            field=models.CharField(default='v1', help_text='BOM version (e.g. v1, v2, 2081-A).', max_length=20),
        ),
        migrations.AlterField(
            model_name='billofmaterials',
            name='yield_quantity',
            field=models.DecimalField(decimal_places=3, default=Decimal('1.000'), help_text='Quantity of finished product produced per BOM run.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='billofmaterials',
            name='yield_unit',
            field=models.CharField(default='pcs', help_text='Unit of the finished product (pcs, kg, litre, etc.)', max_length=20),
        ),
        migrations.AlterField(
            model_name='bomitem',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bomitem',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bomitem',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bomitem',
            name='quantity',
            field=models.DecimalField(decimal_places=3, help_text='Quantity needed per BOM yield.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='bomitem',
            name='raw_material',
            field=models.ForeignKey(help_text='Raw material or sub-assembly.', on_delete=django.db.models.deletion.CASCADE, related_name='used_in_boms', to='products.product'),
        ),
        migrations.AlterField(
            model_name='bomitem',
            name='scrap_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Expected scrap/waste percentage.', max_digits=5),
        ),
        migrations.AlterField(
            model_name='bomitem',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='machine',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='machine',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='machine',
            name='hourly_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Operating cost per hour.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='machine',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='machine',
            name='machine_type',
            field=models.CharField(blank=True, help_text='e.g. CNC, Lathe, Mixer, Conveyor', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='machine',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='machinelog',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Cost of maintenance/repair if applicable.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='machinelog',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='machinelog',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='machinelog',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='machinelog',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='productionrun',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='productionrun',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='productionrun',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productionrun',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='qualitycheck',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='qualitycheck',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='qualitycheck',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='qualitycheck',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='bom',
            field=models.ForeignKey(help_text='BOM to use for this production run.', on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='manufacturing.billofmaterials'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='sales_order',
            field=models.ForeignKey(blank=True, help_text='Sales order that triggered this work order (optional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders', to='orders.salesorder'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workordermaterial',
            name='bom_item',
            field=models.ForeignKey(blank=True, help_text='BOM item this consumption is for.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='manufacturing.bomitem'),
        ),
        migrations.AlterField(
            model_name='workordermaterial',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workordermaterial',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workordermaterial',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='workordermaterial',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Cost per unit at time of consumption.', max_digits=14),
        ),
        migrations.AlterField(
            model_name='workordermaterial',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
    ]
