# Generated by Django 5.2.3 on 2025-07-14 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0008_remove_ledgeraccount_opening_type'),
        ('vendors', '0002_alter_vendor_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='related_ledger_account',
            field=models.OneToOneField(blank=True, help_text="Automatically assigned ledger account for this vendor's payables.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_accounts', to='bookkeeping.ledgeraccount'),
        ),
    ]
