# Generated by Django 6.0.4 on 2026-06-02 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0003_vendor_related_ledger_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='pan_number',
            field=models.CharField(blank=True, help_text='PAN / VAT registration number', max_length=20, null=True),
        ),
    ]
