# Generated by Django 6.0.4 on 2026-06-21 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0003_alter_possale_payment_method'),
        ('vendors', '0004_add_pan_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='ref_by',
            field=models.ForeignKey(blank=True, help_text='Person who referred this vendor.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_vendors', to='pos.referrer'),
        ),
    ]
