# Generated by Django 6.0.4 on 2026-07-02 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0005_vendor_ref_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='vat_registered',
            field=models.BooleanField(default=False, help_text='Is this vendor VAT registered?'),
        ),
    ]
