# Generated by Django 6.0.4 on 2026-06-14 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='report_type',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
