# Generated by Django 6.0.4 on 2026-06-16 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_referrer_possale_referred_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='possale',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('BANK_TRANSFER', 'Bank Transfer'), ('CHEQUE', 'Cheque'), ('OTHER', 'Other')], help_text='Method used at checkout (CASH, BANK_TRANSFER, etc.).', max_length=20),
        ),
    ]
