# Generated by Django 6.0.4 on 2026-06-25 09:55

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0003_alter_possale_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='possale',
            name='delivery_charge',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
