# Generated by Django 6.0.4 on 2026-07-31 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0013_bankreconciliation'),
        ('pos', '0004_pos_sale_delivery_charge'),
    ]

    operations = [
        migrations.AddField(
            model_name='possale',
            name='bank_account',
            field=models.ForeignKey(blank=True, help_text='Bank account the payment was received into (BANK_TRANSFER only).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos_sales', to='payments.bankaccount'),
        ),
        migrations.AlterField(
            model_name='possale',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('BANK_TRANSFER', 'Bank'), ('DUE', 'Due')], help_text='Method used at checkout (CASH, BANK_TRANSFER, DUE).', max_length=20),
        ),
    ]
