# Generated by Django 6.0.4 on 2026-08-11 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0004_pos_sale_delivery_charge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='possale',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('BANK_TRANSFER', 'Bank Transfer'), ('CHEQUE', 'Cheque'), ('OTHER', 'Other'), ('CREDIT', 'Credit (Pay Later)')], help_text='Method used at checkout (CASH, BANK_TRANSFER, CREDIT, etc.).', max_length=20),
        ),
    ]
