# Generated by Django 6.0.4 on 2026-08-11 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0006_alter_possale_payment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='possale',
            name='bank_account',
        ),
    ]
