# Generated by Django 5.2.3 on 2025-06-30 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0006_ledgeraccount_opening_type_ledgeropeningbalance'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledgeraccount',
            name='system_created',
            field=models.BooleanField(default=False),
        ),
    ]
