# Generated by Django 6.0.4 on 2026-05-29 16:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0011_ledgeraccount_is_current'),
        ('company', '0013_company_cit_rate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FixedAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
                ('asset_code', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(blank=True, help_text='e.g. Furniture, Computers, Vehicles, Buildings', max_length=100, null=True)),
                ('cost', models.DecimalField(decimal_places=2, help_text='Original acquisition cost including all costs to bring asset to working condition', max_digits=14)),
                ('residual_value', models.DecimalField(decimal_places=2, default=0, help_text='Estimated scrap/salvage value at end of useful life', max_digits=14)),
                ('useful_life_years', models.PositiveSmallIntegerField(help_text='Estimated useful life in years')),
                ('depreciation_method', models.CharField(choices=[('SLM', 'Straight-Line Method (SLM)'), ('WDV', 'Written Down Value / Diminishing Balance (WDV)')], default='SLM', max_length=3)),
                ('depreciation_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Annual rate % for WDV method. Leave blank for SLM (auto-computed).', max_digits=5, null=True)),
                ('acquisition_date', models.DateField(help_text='Date asset was put into service')),
                ('disposal_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('DISPOSED', 'Disposed'), ('IMPAIRED', 'Impaired')], default='ACTIVE', max_length=10)),
                ('accumulated_depreciation', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('accumulated_dep_account', models.ForeignKey(blank=True, help_text='Accumulated depreciation contra-asset account', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fixed_assets_accum_dep', to='bookkeeping.ledgeraccount')),
                ('asset_account', models.ForeignKey(blank=True, help_text='Asset cost account (ASSET type)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fixed_assets_asset', to='bookkeeping.ledgeraccount')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixed_assets', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('depreciation_expense_account', models.ForeignKey(blank=True, help_text='Depreciation expense account (EXPENSE type)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fixed_assets_dep_expense', to='bookkeeping.ledgeraccount')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FixedAssetDepreciationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depreciation_logs', to='bookkeeping.fixedasset')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookkeeping.journalentry')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-period_end'],
            },
        ),
    ]
