# Generated by Django 6.0.4 on 2026-06-01 07:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0012_fixedasset_fixedassetdepreciationlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='journalentryline',
            index=models.Index(fields=['account', 'entry_type'], name='jel_account_type_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentryline',
            index=models.Index(fields=['journal_entry', 'entry_type'], name='jel_entry_type_idx'),
        ),
    ]
