# Generated by Django 6.0.4 on 2026-07-21 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0018_fn_invoice_journal_soft_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledgeraccount',
            name='normal_balance',
            field=models.CharField(blank=True, choices=[('DEBIT', 'Debit'), ('CREDIT', 'Credit')], help_text='NFRS: the entry_type (DEBIT/CREDIT) that increases this account. Auto-derived from account_type if left blank.', max_length=10),
        ),
    ]
