# Generated by Django 6.0.4 on 2026-04-29 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_category_company_alter_product_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='hscode',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='HS Code'),
        ),
    ]
