# Generated by Django 6.0.4 on 2026-05-24 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_stocktransaction_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktransaction',
            name='stock_type',
            field=models.CharField(choices=[('POS', 'POS Stock'), ('ECOM', 'E-commerce Stock')], default='POS', max_length=10),
        ),
    ]
