# Generated by Django 6.0.4 on 2026-06-02 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_cost_method_product_nrv'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='short_description',
            field=models.CharField(blank=True, help_text='Brief product summary for e-commerce listings (max 500 chars)', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='ecom_description',
            field=models.TextField(blank=True, help_text='Full product description shown on the e-commerce store', null=True),
        ),
    ]
