# Generated by Django 6.0.4 on 2026-06-07 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_product_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='ecom_image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/'),
        ),
    ]
