# Generated by Django 6.0.4 on 2026-06-21 06:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_product_vendor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='conversion_factor',
            field=models.DecimalField(decimal_places=4, default=1, help_text='How many sale units equal 1 purchase unit (e.g. 1000 for KG→Gram, 12 for Dozen→Piece).', max_digits=12),
        ),
        migrations.AddField(
            model_name='product',
            name='has_variants',
            field=models.BooleanField(default=False, help_text='Enable size/color variants (clothes, shoes). Stock tracked per variant when enabled.'),
        ),
        migrations.CreateModel(
            name='UnitOfMeasure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('symbol', models.CharField(max_length=10)),
                ('uom_type', models.CharField(choices=[('WEIGHT', 'Weight (kg, gram, etc.)'), ('COUNT', 'Count (pcs, dozen, etc.)'), ('LENGTH', 'Length (meter, cm, etc.)'), ('VOLUME', 'Volume (liter, ml, etc.)')], default='COUNT', max_length=10)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='product',
            name='purchase_unit',
            field=models.ForeignKey(blank=True, help_text='Unit in which this product is received (e.g. KG, Dozen).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchased_products', to='products.unitofmeasure'),
        ),
        migrations.AddField(
            model_name='product',
            name='sale_unit',
            field=models.ForeignKey(blank=True, help_text='Unit in which this product is sold (e.g. Gram, Piece).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sold_products', to='products.unitofmeasure'),
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('size', models.CharField(blank=True, default='', help_text='e.g. S, M, L, XL or 6, 7, 8, 9, 10', max_length=20)),
                ('color', models.CharField(blank=True, default='', help_text='e.g. Red, Blue, Black', max_length=50)),
                ('sku', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('barcode', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('price_adjustment', models.DecimalField(decimal_places=2, default=0, help_text='Added to or subtracted from product base price for this variant.', max_digits=10)),
                ('stock', models.PositiveIntegerField(default=0, help_text='POS/in-store stock in sale units.')),
                ('ecom_stock', models.PositiveIntegerField(default=0, help_text='E-commerce stock in sale units.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.product')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('product', 'size', 'color')},
            },
        ),
    ]
