# Generated by Django 6.0.4 on 2026-06-24 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_product_compare_at_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='compare_at_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='ecom_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='ecom_image',
            field=models.ImageField(blank=True, null=True, upload_to='packages/'),
        ),
        migrations.AddField(
            model_name='package',
            name='show_on_ecom',
            field=models.BooleanField(default=False),
        ),
    ]
