# Generated by Django 6.0.4 on 2026-05-24 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_add_ecom_fields_to_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='productstock',
            name='ecom_minimum_stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productstock',
            name='ecom_stock',
            field=models.PositiveIntegerField(default=0, help_text='Stock reserved specifically for E-commerce.'),
        ),
        migrations.AlterField(
            model_name='productstock',
            name='stock',
            field=models.PositiveIntegerField(default=0, help_text='Stock available for POS/In-store sales.'),
        ),
    ]
