# Generated by Django 6.0.4 on 2026-05-29 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_stocktransaction_stock_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cost_method',
            field=models.CharField(choices=[('FIFO', 'First-In First-Out (FIFO)'), ('WA', 'Weighted Average Cost')], default='WA', help_text='NFRS 2: inventory cost formula used for COGS and stock valuation.', max_length=4),
        ),
        migrations.AddField(
            model_name='product',
            name='nrv',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='NFRS 2: Net Realisable Value. If NRV < cost_price, inventory must be written down.', max_digits=10, null=True),
        ),
    ]
