# Generated by Django 6.0.4 on 2026-06-05 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_add_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='image_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
