# Generated by Django 6.0.4 on 2026-06-06 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_productimage_image_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, default='', help_text='Product color for storefront filter (e.g. Red, Blue)', max_length=50),
        ),
    ]
