# Generated by Django 6.0.4 on 2026-06-16 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_product_sku'),
        ('vendors', '0004_add_pan_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='vendor',
            field=models.ForeignKey(blank=True, help_text='Preferred vendor to purchase this item from.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='vendors.vendor'),
        ),
    ]
