# Generated by Django 6.0.4 on 2026-07-30 03:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0022_fn_close_period_journal_type'),
        ('products', '0019_packageitem_item_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktransaction',
            name='disposal_reason',
            field=models.CharField(blank=True, choices=[('DAMAGED', 'Damaged'), ('EXPIRED', 'Expired'), ('LOST', 'Lost'), ('THEFT', 'Theft'), ('OBSOLETE', 'Obsolete'), ('OTHER', 'Other')], help_text='NFRS 2: category of write-off. Only set when transaction_type=DISPOSAL.', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='journal_entry',
            field=models.ForeignKey(blank=True, help_text='The write-off journal entry posted for a DISPOSAL transaction.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookkeeping.journalentry'),
        ),
        migrations.AlterField(
            model_name='stocktransaction',
            name='transaction_type',
            field=models.CharField(choices=[('ADD', 'Add Stock'), ('REMOVE', 'Remove Stock'), ('ADJUST', 'Adjust Stock'), ('DISPOSAL', 'Disposal / Write-off')], max_length=20),
        ),
    ]
